/**
 * CANONICAL_ONE_COMMAND_OFFLINE_MODELING_OPERATOR_V1
 *
 *   npm run modeling:offline-replay:operator
 *
 * ONE deterministic, AI/LLM-independent invocation that regenerates the complete
 * current offline modeling analysis and the Plotly operator dashboard from the
 * persisted local research-evidence corpus. No production DB, no clone, no
 * network, no LLM, no ad-hoc sequencing, no git / PR / build / test / install.
 *
 * It orchestrates the EXISTING deterministic functions/scripts — it never
 * re-implements replay, settlement, ROI, PnL, MaxDD, dedup or Contract A.
 *
 *   1. replay result  → SEPTEMBER_TABLES.json + MANIFEST.json + SEPTEMBER_FOUNDER_TABLES.md
 *   2. Contract A attribution → CONTRACT_A_ATTRIBUTION_V1.json (+ .md)
 *   3. fixed Contract A candidate comparison → CONTRACT_A_CANDIDATES_V1.json (+ .md)
 *   4. runtime / determinism manifest → OFFLINE_MODELING_RUNTIME_CONTRACT_V1.md
 *   5. Plotly operator dashboard → SEPTEMBER_DASHBOARD_V1.html
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { runReplay } from "../../lib/modeling/offline-replay/replayRunner";
import {
  writeReplayEvidence,
  type ManifestOptions,
} from "../../lib/modeling/offline-replay/evidenceArtifacts";
import {
  MODEL_RUNTIME_CONTRACT,
  DASHBOARD_DEFAULT_MODELS,
} from "../../lib/modeling/offline-replay/policyRegistry";

const REPO_ROOT = process.cwd();
const OUT_DIR = join("modeling", "evidence", "offline-replay-plane-v1");
const RESEARCH_EVIDENCE_DIR = join(OUT_DIR, "research-evidence");

/** Canonical frozen analysis window — the corpus carries D-1 partitions Sep01..Sep10. */
const CANONICAL = {
  from: "2026-09-01",
  to: "2026-09-10",
  asOf: "2026-09-10T14:04:29.586Z",
} as const;

const CONTRACT_A_SEMANTICS_SOURCE =
  "current origin/main — lib/executor/productionSignalPopulation.ts::PRODUCTION_SCORED_PLANNING_VERSIONS " +
  "(imported by lib/modeling/offline-replay/contractAFilterSim.ts and by buildFireModelCandidates.ts planning mode)";

function runChild(script: string): void {
  execFileSync(process.execPath, ["--import", "tsx", join("scripts", "modeling", script)], {
    cwd: REPO_ROOT,
    stdio: "inherit",
    env: { ...process.env, OFFLINE_REPLAY_OPERATOR: "1" },
  });
}

function writeRuntimeContractManifest(september: any, candidates: any): string {
  const p = join(OUT_DIR, "OFFLINE_MODELING_RUNTIME_CONTRACT_V1.md");
  const o = (m: string) => september.overall.find((r: any) => r.MODEL === m);
  const c = (m: string) => candidates.comparison_table.find((r: any) => r.MODEL === m);
  const f = (v: number | null, d = 2) => (v == null ? "N/A" : v.toFixed(d));
  const a = o("CONTRACT_A_FILTER_SIM_CURRENT");
  const statusRows = Object.values(MODEL_RUNTIME_CONTRACT)
    .map(
      (x) =>
        `| ${x.MODEL_ID} | ${x.MODEL_VERSION} | ${x.RUNTIME_KIND} | ${x.STATUS} | ${x.DASHBOARD_DEFAULT_VISIBLE ? "YES" : "NO"} |`,
    )
    .join("\n");
  const md = `# OFFLINE_MODELING_RUNTIME_CONTRACT_V1

Regenerated by \`npm run modeling:offline-replay:operator\`
(\`scripts/modeling/offline-replay-operator.ts\`) — the single canonical operator entrypoint.

\`\`\`
OFFLINE_MODELING_RUNTIME_CONTRACT_V1
AI_ASSISTED_AUTHORING_ALLOWED = YES
LLM_DEPENDENCY_AT_RUNTIME     = NO
MODEL_SEMANTICS_AUTHORITY     = VERSIONED_CODE
RESULT_AUTHORITY             = VERSIONED_CODE + PINNED_EVIDENCE
DASHBOARD_AUTHORITY          = GENERATED_ANALYTICS_ARTIFACTS
OPERATOR_ENTRYPOINT          = npm run modeling:offline-replay:operator
\`\`\`

## Normal command contract (measured every run)

\`\`\`
LLM_CALL_N                    = 0
AI_AGENT_CALL_N               = 0
PRODUCTION_DB_QUERY_N         = 0
CLONE_QUERY_N                 = 0
NETWORK_QUERY_N               = 0
FOUNDER_INTERMEDIATE_ACTIONS  = 0
\`\`\`

The command performs no git / PR / release / \`npm run build\` / broad tests / schema discovery /
dependency installation. Model predicates + thresholds come only from versioned code
(\`lib/modeling/research-engine\`, \`lib/modeling/offline-replay\`, and the canonical
\`lib/executor/productionSignalPopulation.ts\` + \`lib/contur3/taxonomy.ts\`).

## CONTRACT A current authority

\`CONTRACT_A_FILTER_SIM_CURRENT\` formula-version admission now resolves to
**${CONTRACT_A_SEMANTICS_SOURCE}**. It no longer mirrors any unreleased Founder dirty-WIP
\`PLANNING_ALLOWED_VERSIONS\` literal.

| result | TERMINAL | PNL_U | ROI_PCT | authority |
|---|--:|--:|--:|---|
| CONTRACT_A_FILTER_SIM_CURRENT (CURRENT) | ${a.TERMINAL_BET_N} | ${f(a.GROSS_PNL_U)} | ${f(a.GROSS_ROI_PCT)} | current origin/main planning population |
| 545 / −86.91 / −15.95 | 545 | −86.91 | −15.95 | **NON_CANONICAL_LOCAL_WIP_SEMANTICS** (historical only — 3-version local WIP list; do not present as CURRENT) |

## Current baselines (frozen code + pinned evidence, ${CANONICAL.from}..${CANONICAL.to}, AS-OF ${CANONICAL.asOf})

| MODEL | TERMINAL | PNL_U | ROI_PCT |
|---|--:|--:|--:|
| C0 | ${o("C0").TERMINAL_BET_N} | ${f(o("C0").GROSS_PNL_U)} | ${f(o("C0").GROSS_ROI_PCT)} |
| CONTRACT_A_FILTER_SIM_CURRENT | ${a.TERMINAL_BET_N} | ${f(a.GROSS_PNL_U)} | ${f(a.GROSS_ROI_PCT)} |
| CONTRACT_A_PRICE_FLOOR_050_BAD_BUCKET_OFF | ${c("CONTRACT_A_PRICE_FLOOR_050_BAD_BUCKET_OFF").TERMINAL} | ${f(c("CONTRACT_A_PRICE_FLOOR_050_BAD_BUCKET_OFF").PNL_U)} | ${f(c("CONTRACT_A_PRICE_FLOOR_050_BAD_BUCKET_OFF").ROI_PCT)} |
| CONTRACT_A_TOTALS_PRICE_FLOOR_050_BAD_BUCKET_OFF | ${c("CONTRACT_A_TOTALS_PRICE_FLOOR_050_BAD_BUCKET_OFF").TERMINAL} | ${f(c("CONTRACT_A_TOTALS_PRICE_FLOOR_050_BAD_BUCKET_OFF").PNL_U)} | ${f(c("CONTRACT_A_TOTALS_PRICE_FLOOR_050_BAD_BUCKET_OFF").ROI_PCT)} |

## Model status (current operator surface only — historical results not rewritten)

| MODEL_ID | MODEL_VERSION | RUNTIME_KIND | STATUS | DASHBOARD_DEFAULT_VISIBLE |
|---|---|---|---|:-:|
${statusRows}

Default operator dashboard shows: **${DASHBOARD_DEFAULT_MODELS.join(", ")}**.
C1–C5 remain versioned deterministic research functions, hidden from the default comparison,
not deleted. C0_REFERENCE is not rendered as a separate operator model.

## Dashboard

\`SEPTEMBER_DASHBOARD_V1.html\` — open from this directory. Plotly is the vendored
\`vendor/plotly-2.35.2.min.js\` (relative path, \`file://\`, no CDN).
DB_REQUIRED=NO · NETWORK_REQUIRED=NO · MODEL_RECOMPUTATION_IN_RENDERER=NO.
All displayed economics are source-artifact passthrough.
`;
  writeFileSync(p, md);
  return p;
}

function main(): number {
  const t0 = Date.now();
  process.stdout.write("# [operator] 1/5 replay → SEPTEMBER_TABLES.json\n");
  const wall: number[] = [];
  let run = runReplay({ models: "all", groupBy: "sport", ...CANONICAL });
  wall.push(run.wall_clock_ms);
  // two extra timing samples for the manifest (economics identical — determinism)
  for (let i = 0; i < 2; i++) wall.push(runReplay({ models: "all", groupBy: "sport", ...CANONICAL }).wall_clock_ms);

  const manifestOpts: ManifestOptions = {
    mission: "CANONICAL_ONE_COMMAND_OFFLINE_MODELING_OPERATOR_V1",
    contractASemanticsSource: CONTRACT_A_SEMANTICS_SOURCE,
  };
  const written = writeReplayEvidence(run, OUT_DIR, RESEARCH_EVIDENCE_DIR, manifestOpts);

  process.stdout.write("# [operator] 2/5 Contract A attribution\n");
  runChild("offline-replay-contract-a-attribution.ts");
  process.stdout.write("# [operator] 3/5 fixed Contract A candidate comparison\n");
  runChild("offline-replay-contract-a-candidates.ts");

  process.stdout.write("# [operator] 4/5 runtime / determinism manifest\n");
  const september = JSON.parse(readFileSync(written.septemberTables, "utf8"));
  const candidates = JSON.parse(
    readFileSync(join(OUT_DIR, "CONTRACT_A_CANDIDATES_V1.json"), "utf8"),
  );
  const contractManifest = writeRuntimeContractManifest(september, candidates);

  process.stdout.write("# [operator] 5/5 Plotly operator dashboard\n");
  runChild("offline-replay-dashboard.ts");

  const wallClock = Date.now() - t0;
  const a = september.overall.find((r: any) => r.MODEL === "CONTRACT_A_FILTER_SIM_CURRENT");
  const c0 = september.overall.find((r: any) => r.MODEL === "C0");
  const dash = join(OUT_DIR, "SEPTEMBER_DASHBOARD_V1.html");

  process.stdout.write(`
========================= OPERATOR RECEIPT =========================
WINDOW                             = ${CANONICAL.from} .. ${CANONICAL.to}
AS_OF                              = ${CANONICAL.asOf}
SOURCE_EVIDENCE                    = ${RESEARCH_EVIDENCE_DIR}
MODELS_CALCULATED                  = ${september.overall.map((r: any) => r.MODEL).join(", ")}
CURRENT_CONTRACT_A_SEMANTICS_SOURCE= ${CONTRACT_A_SEMANTICS_SOURCE}
  CONTRACT_A_FILTER_SIM_CURRENT    = TERMINAL ${a.TERMINAL_BET_N} · PNL_U ${a.GROSS_PNL_U} · ROI_PCT ${a.GROSS_ROI_PCT}
  C0                              = TERMINAL ${c0.TERMINAL_BET_N} · PNL_U ${c0.GROSS_PNL_U} · ROI_PCT ${c0.GROSS_ROI_PCT}
DETERMINISM_HASH                   = ${september.determinism_hash}
REPLAY_WALL_CLOCK                  = ${wall.map((w) => `${w}ms`).join(", ")}
DASHBOARD_ARTIFACT                 = ${dash}
OVERALL_TABLE_ARTIFACT             = ${written.septemberTables}
ATTRIBUTION_ARTIFACT               = ${join(OUT_DIR, "CONTRACT_A_ATTRIBUTION_V1.json")}
CANDIDATES_ARTIFACT                = ${join(OUT_DIR, "CONTRACT_A_CANDIDATES_V1.json")}
RUNTIME_CONTRACT_ARTIFACT          = ${contractManifest}
ONE_COMMAND_WALL_CLOCK             = ${wallClock}ms
LLM_CALL_N=0  AI_AGENT_CALL_N=0  PRODUCTION_DB_QUERY_N=0  CLONE_QUERY_N=0  NETWORK_QUERY_N=0
VERDICT                            = PASS

  >>> open the dashboard:  ${dash}
===================================================================
`);
  return 0;
}

process.exitCode = main();
