import type { ExecutionCandidate } from "./executionWaterfall";
import { classifyResolvedOutcome } from "./roiPnlContract";
import type { TerminalExecutionResult } from "./pnlFirstStakeAllocator";

export interface CapacityAttributionRow {observationId:string;terminalResult:TerminalExecutionResult;maximumStake:number;executableTier:0|.3|.5|.7|1;entryPrice:number;decisionAtIso:string;overlapPositions:number;counterfactualFlatOneUnitPnl:number;counterfactualFixedMaximumPnl:number}
export interface CapacityAttribution {candidateMatches:number;executedMatches:number;nonExecutedMatches:number;couldExecuteAt70:number;couldExecuteAt50:number;couldExecuteAt30:number;couldNotExecuteAt30:number;reasonCounts:Record<string,number>;rows:CapacityAttributionRow[]}
const round=(x:number)=>Math.round(x*1e8)/1e8;
export function attributeFixedMaximumCapacity(candidates:readonly ExecutionCandidate[]):CapacityAttribution{
  const ordered=[...candidates].sort((a,b)=>Date.parse(a.decisionAtIso)-Date.parse(b.decisionAtIso)||b.finalScore-a.finalScore||b.dataCoverage-a.dataCoverage||a.entryPrice-b.entryPrice||Date.parse(a.createdAtIso)-Date.parse(b.createdAtIso)||a.observationId.localeCompare(b.observationId));
  let free=50,reference=50,currentDay="";const open:Array<{c:ExecutionCandidate;stake:number,resolved:number}>=[],acceptedByDay=new Map<string,number>(),rows:CapacityAttributionRow[]=[];
  for(const c of ordered){const at=Date.parse(c.decisionAtIso);for(const position of [...open].filter(x=>x.resolved<=at).sort((a,b)=>a.resolved-b.resolved||a.c.observationId.localeCompare(b.c.observationId))){open.splice(open.indexOf(position),1);const win=classifyResolvedOutcome(position.c.row).label==="win";free=round(free+position.stake+(win?position.stake*(1/position.c.entryPrice-1):-position.stake))}
    const day=c.decisionAtIso.slice(0,10);if(day!==currentDay){currentDay=day;reference=free+open.reduce((s,x)=>s+x.stake,0)}const maximum=.03*reference,exposure=open.reduce((s,x)=>s+x.stake,0),outcome=classifyResolvedOutcome(c.row);let terminalResult:TerminalExecutionResult="EXECUTED_FULL",tier:0|.3|.5|.7|1=1;
    if(!Number.isFinite(Date.parse(c.resolvedAtIso))||outcome.label==="invalid"){terminalResult="INVALID_SETTLEMENT";tier=0}else if(open.length>=30){terminalResult="POSITION_LIMIT";tier=0}else if((acceptedByDay.get(day)??0)>=100){terminalResult="DAILY_LIMIT";tier=0}else{const feasible=(t:number)=>exposure+t*maximum<=.8*reference+1e-9&&t*maximum<=free+1e-9;if(!feasible(1)){tier=feasible(.7)?.7:feasible(.5)?.5:feasible(.3)?.3:0;terminalResult=tier===.7?"EXECUTED_70":tier===.5?"EXECUTED_50":tier===.3?"EXECUTED_30":exposure+.3*maximum>.8*reference+1e-9?"OPEN_EXPOSURE_LIMIT":"INSUFFICIENT_ACTIVE_CAPACITY"}}
    const flat=outcome.label==="win"?1/c.entryPrice-1:outcome.label==="loss"?-1:0;rows.push({observationId:c.observationId,terminalResult,maximumStake:round(maximum),executableTier:tier,entryPrice:c.entryPrice,decisionAtIso:c.decisionAtIso,overlapPositions:open.length,counterfactualFlatOneUnitPnl:round(flat),counterfactualFixedMaximumPnl:round(flat*maximum)});
    if(tier>0){const stake=round(tier*maximum);free=round(free-stake);open.push({c,stake,resolved:Date.parse(c.resolvedAtIso)});acceptedByDay.set(day,(acceptedByDay.get(day)??0)+1)}
  }
  const non=rows.filter(x=>x.executableTier===0);return{candidateMatches:rows.length,executedMatches:rows.length-non.length,nonExecutedMatches:non.length,couldExecuteAt70:non.filter(x=>x.executableTier===.7).length,couldExecuteAt50:non.filter(x=>x.executableTier===.5).length,couldExecuteAt30:non.filter(x=>x.executableTier===.3).length,couldNotExecuteAt30:non.filter(x=>x.executableTier===0).length,reasonCounts:Object.fromEntries([...new Set(rows.map(x=>x.terminalResult))].sort().map(reason=>[reason,rows.filter(x=>x.terminalResult===reason).length])),rows};
}
