import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { gunzipSync } from "node:zlib";
import { deriveHistoricalSportingMatchKeyV1 } from "./historicalSportingMatchIdentity";

export type Confidence="HIGH"|"MEDIUM"|"LOW"|"UNRESOLVED"|"NOT_APPLICABLE";
export type Resolution={raw:string|null;canonical:string|null;confidence:Confidence;provenance:Record<string,unknown>|null;conflict:boolean;warning:string|null};
export const round=(n:number)=>Number(n.toFixed(8));
export const canonicalizeLabel=(v:string)=>v.normalize("NFKD").replace(/[^\p{L}\p{N}]+/gu," ").trim().toUpperCase();
const first=(o:Record<string,any>,keys:string[])=>keys.map(k=>o[k]).find(v=>typeof v==="string"&&v.trim()) as string|undefined;
const provenance=(fields:string[],raw:string,canonical:string,confidence:Confidence,resolver:string)=>({sourcePath:"modeling/canonical/datasets/2026-07-15-b2f5dfb5963e/generated_signal_pairs_export.json.gz",sourceFields:fields,resolver,rawValue:raw,canonicalValue:canonical,confidence});
const MLB=/Yankees|Mets|Red Sox|White Sox|Cubs|Dodgers|Giants|Padres|Phillies|Pirates|Guardians|Tigers|Twins|Royals|Rangers|Astros|Angels|Athletics|Mariners|Rays|Marlins|Braves|Nationals|Orioles|Blue Jays|Brewers|Cardinals|Rockies|Diamondbacks|Reds/i;
const NBA=/Knicks|Spurs|Thunder|Cavaliers/i, WNBA=/Fever|Mystics|Sky|Dream|Wings|Sparks|Liberty/i, NHL=/Hurricanes|Canadiens|Avalanche|Golden Knights/i;
const TENNIS=/Roland Garros|\bATP\b|\bWTA\b|Set \d Winner|Match O\/U|Zverev|Fritz|Pliskova|Bouzkova|Berrettini|Cilic|Vekic|Tiafoe/i;
const ESPORTS=/Map Handicap|Game Handicap|Gaming|TYLOO|Aurora|G2|GEN|T1|M80|KT Rolster|GIANTX|LGC|Team Secret|FUT|B8/i;
function directResolution(row:Record<string,any>,keys:string[],resolver:string):Resolution|null{const vals=keys.map(k=>[k,row[k]] as const).filter(([,v])=>typeof v==="string"&&v.trim());if(!vals.length)return null;const canon=[...new Set(vals.map(([,v])=>canonicalizeLabel(v)))];if(canon.length>1)return{raw:vals.map(([,v])=>v).join(" | "),canonical:null,confidence:"UNRESOLVED",provenance:null,conflict:true,warning:`CONFLICTING_${resolver.toUpperCase()}_FIELDS`};const raw=vals[0][1],canonical=canon[0];return{raw,canonical,confidence:"HIGH",provenance:provenance(vals.map(([k])=>k),raw,canonical,"HIGH",resolver),conflict:false,warning:null};}
export function resolveSport(row:Record<string,any>):Resolution{const direct=directResolution(row,["sport","sports","sportType"],"resolveSport/direct-v1");if(direct)return direct;const title=first(row,["eventTitle","event_slug","marketTitle","market_slug"]);if(!title)return{raw:null,canonical:null,confidence:"UNRESOLVED",provenance:null,conflict:false,warning:"NO_SPORT_EVIDENCE"};let canonical:string|null=MLB.test(title)?"BASEBALL":WNBA.test(title)||NBA.test(title)?"BASKETBALL":NHL.test(title)?"ICE HOCKEY":TENNIS.test(title)?"TENNIS":ESPORTS.test(title)?"ESPORTS":/vs\.|beat|Match Winner|score first|Halftime|Total Corners|Spread:/i.test(title)?"SOCCER":null;return canonical?{raw:title,canonical,confidence:"LOW",provenance:provenance(["event_slug","market_slug"],title,canonical,"LOW","resolveSport/title-v1"),conflict:false,warning:"TITLE_FALLBACK"}:{raw:title,canonical:null,confidence:"UNRESOLVED",provenance:null,conflict:false,warning:"UNRECOGNIZED_TITLE_SPORT"};}
export function resolveLeagueCompetition(row:Record<string,any>):Resolution{const direct=directResolution(row,["league","competition","tournament","series"],"resolveLeagueCompetition/direct-v1");if(direct)return direct;const title=first(row,["eventTitle","event_slug"]);if(!title)return{raw:null,canonical:null,confidence:"UNRESOLVED",provenance:null,conflict:false,warning:"NO_LEAGUE_EVIDENCE"};const sport=resolveSport(row).canonical;let canonical:string|null=sport==="BASEBALL"?"MLB":sport==="BASKETBALL"?(WNBA.test(title)?"WNBA":"NBA"):sport==="ICE HOCKEY"?"NHL":/Roland Garros ATP/i.test(title)?"ATP ROLAND GARROS":/Roland Garros WTA/i.test(title)?"WTA ROLAND GARROS":sport==="TENNIS"?"TENNIS COMPETITION UNSPECIFIED":sport==="ESPORTS"?"ESPORTS COMPETITION UNSPECIFIED":sport==="SOCCER"?"SOCCER COMPETITION UNSPECIFIED":null;return canonical?{raw:title,canonical,confidence:"LOW",provenance:provenance(["event_slug"],title,canonical,"LOW","resolveLeagueCompetition/title-v1"),conflict:false,warning:"TITLE_FALLBACK"}:{raw:title,canonical:null,confidence:"UNRESOLVED",provenance:null,conflict:false,warning:"UNRECOGNIZED_LEAGUE"};}
const MARKET_MAP:Record<string,string>={moneyline:"MONEYLINE",child_moneyline:"MONEYLINE",three_way_moneyline:"THREE_WAY_MONEYLINE",spread:"SPREAD",handicap:"HANDICAP",map_handicap:"HANDICAP",round_handicap:"HANDICAP",total:"TOTAL",totals:"TOTAL",total_corners:"TOTAL",over_under:"TOTAL",halftime_result:"HALF_FULL_TIME",soccer_halftime_result:"HALF_FULL_TIME",both_teams_to_score:"BOTH_TEAMS_TO_SCORE"};
export function resolveMarketFamily(row:Record<string,any>):Resolution{const raw=first(row,["marketType","sportsMarketType","market_type"]);if(raw){const base=raw.toLowerCase().replace(/_(game|map|set|period|quarter|half)_\d+$/,"");const canonical=MARKET_MAP[raw.toLowerCase()]??MARKET_MAP[base]??null;return canonical?{raw,canonical,confidence:"HIGH",provenance:provenance(["marketType","sportsMarketType","market_type"],raw,canonical,"HIGH","resolveMarketFamily/repository-map-v1"),conflict:false,warning:null}:{raw,canonical:null,confidence:"UNRESOLVED",provenance:null,conflict:false,warning:"UNSUPPORTED_MARKET_TYPE"};}const title=first(row,["eventTitle","event_slug","marketTitle","market_slug"]);if(!title)return{raw:null,canonical:null,confidence:"UNRESOLVED",provenance:null,conflict:false,warning:"NO_MARKET_EVIDENCE"};const canonical=/Both Teams to Score/i.test(title)?"BOTH_TEAMS_TO_SCORE":/Halftime|1H /i.test(title)?"HALF_FULL_TIME":/O\/U|Total Corners/i.test(title)?"TOTAL":/Spread:/i.test(title)?"SPREAD":/Handicap:/i.test(title)?"HANDICAP":/Match Winner|Set \d Winner|score first|beat|vs\.?/i.test(title)?"MONEYLINE":null;return canonical?{raw:title,canonical,confidence:"LOW",provenance:provenance(["event_slug","market_slug"],title,canonical,"LOW","resolveMarketFamily/title-v1"),conflict:false,warning:"TITLE_FALLBACK"}:{raw:title,canonical:null,confidence:"UNRESOLVED",provenance:null,conflict:false,warning:"UNRECOGNIZED_MARKET_FAMILY"};}

export function loadFrozenDatasetSchema(root:string){const path="modeling/canonical/datasets/2026-07-15-b2f5dfb5963e/generated_signal_pairs_export.json.gz";const rows=JSON.parse(gunzipSync(readFileSync(`${root}/${path}`)).toString("utf8"));return{path,rows,schemaKeys:[...new Set(rows.flatMap((r:any)=>Object.keys(r)))].sort()};}
export function loadLockedAuditRows(root:string){return JSON.parse(readFileSync(`${root}/modeling/evidence/2026-07-17-suspicious-growth-temporal-audit-v1/joined_231_observations.json`,"utf8"));}
export function inventoryAttributionFields(corpus:any[],lockedIds:Set<string>){const fields=["sport","sports","sportType","league","competition","tournament","series","marketType","sportsMarketType","marketFamily","event_slug","market_slug","diagnostics.marketType","diagnostics.marketFamily"];const get=(r:any,p:string)=>p.split(".").reduce((v,k)=>v?.[k],r);return fields.map(field=>{const all=corpus.filter(r=>get(r,field)!=null),locked=all.filter(r=>lockedIds.has(r.id));return{field,sourceArtifact:"modeling/canonical/datasets/2026-07-15-b2f5dfb5963e/generated_signal_pairs_export.json.gz",corpusCoverage:all.length,lockedCoverage:locked.length,examples:[...new Set(locked.map(r=>String(get(r,field))))].slice(0,5),existingResolver:field.includes("marketType")?"sportMarketPerformanceSlice.classifyMarketTypeV2":"historicalAttributionRepair title fallback",sourceConfidence:locked.length?"DIRECT":"ABSENT_IN_LOCKED_ROWS"};});}
export function joinAttributionToAuditRows(audit:any[],corpus:any[]){const byId=new Map(corpus.map(r=>[r.id,r]));return audit.map((a:any)=>{const raw:any=byId.get(a.observationId)??{},merged={...raw,...a,eventTitle:a.eventTitle??raw.event_slug,marketTitle:a.marketTitle??raw.market_slug};const sport=resolveSport(merged),league=resolveLeagueCompetition(merged),market=resolveMarketFamily(merged),identity=deriveHistoricalSportingMatchKeyV1(raw);return{...a,sportRaw:sport.raw,sportCanonical:sport.canonical,leagueRaw:league.raw,leagueCanonical:league.canonical,competitionRaw:league.raw,competitionCanonical:league.canonical,marketTypeRaw:market.raw,marketFamilyCanonical:market.canonical,historicalDerivedMatchKey:identity.key,sportProvenance:sport.provenance,leagueProvenance:league.provenance,marketFamilyProvenance:market.provenance,sportConfidence:sport.confidence,leagueConfidence:league.confidence,marketFamilyConfidence:market.confidence,attributionWarnings:[sport.warning,league.warning,market.warning].filter(Boolean),attributionConflicts:[sport,league,market].filter(x=>x.conflict).map(x=>x.warning)};});}
export function validateResolvedAttribution(rows:any[],expectedIds:string[]){const count=new Map<string,number>();rows.forEach(r=>count.set(r.observationId,(count.get(r.observationId)??0)+1));const duplicateIds=[...count].filter(([,n])=>n>1).map(([id])=>id),missingIds=expectedIds.filter(id=>!count.has(id)),canonicalWithoutProvenance:string[]=[];for(const r of rows)for(const d of ["sport","league","marketFamily"])if(r[`${d}Canonical`]&&!r[`${d}Provenance`])canonicalWithoutProvenance.push(`${r.observationId}:${d}`);return{represented:rows.length,unique:count.size,duplicateIds,missingIds,canonicalWithoutProvenance,pass:rows.length===expectedIds.length&&!duplicateIds.length&&!missingIds.length&&!canonicalWithoutProvenance.length};}
export function attributionCoverage(rows:any[]){const one=(d:string)=>Object.fromEntries(["HIGH","MEDIUM","LOW","UNRESOLVED","NOT_APPLICABLE"].map(c=>[c,rows.filter(r=>r[`${d}Confidence`]===c).length]));return{total:rows.length,sport:one("sport"),league:one("league"),marketFamily:one("marketFamily"),trustedDefinition:"HIGH_OR_MEDIUM"};}
const minsk=(iso:string)=>new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Minsk",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(iso));
export function calculateAttributedWindowSegments(rows:any[],dimension:string,mode:"early"|"post9",pnlField="fixedRealizedPnl"){const selected=rows.filter(r=>mode==="early"?r.resolvedAtIso&&minsk(r.resolvedAtIso)>="2026-05-29"&&minsk(r.resolvedAtIso)<="2026-06-07":r.decisionAtIso&&minsk(r.decisionAtIso)>="2026-06-09");const m=new Map<string,any>();for(const r of selected){const k=String(r[dimension]??"UNRESOLVED"),v=m.get(k)??{segment:k,decisionCount:0,executedCount:0,wins:0,losses:0,stake:0,pnl:0,maximumSinglePositionContribution:-Infinity};v.decisionCount++;const fixedOneUnit=mode==="post9"&&pnlField==="fixedRealizedPnl";if(fixedOneUnit||r[`${pnlField.startsWith("dynamic")?"dynamic":"fixed"}TerminalReason`]?.startsWith("EXECUTED"))v.executedCount++;v.wins+=r.result==="win"?1:0;v.losses+=r.result==="loss"?1:0;const stake=fixedOneUnit?1:Number(r[pnlField.startsWith("dynamic")?"dynamicStake":"fixedStake"]??0),pnl=fixedOneUnit?(r.result==="win"&&r.entryPrice?(1/Number(r.entryPrice))-1:r.result==="loss"?-1:0):Number(r[pnlField]??0);v.stake+=stake;v.pnl+=pnl;v.maximumSinglePositionContribution=Math.max(v.maximumSinglePositionContribution,pnl);m.set(k,v)}const totalPnl=[...m.values()].reduce((a,v)=>a+v.pnl,0);return[...m.values()].map(v=>({...v,stake:round(v.stake),pnl:round(v.pnl),roiPct:v.stake?round(100*v.pnl/v.stake):0,pnlSharePct:totalPnl?round(100*v.pnl/totalPnl):0,averageContribution:round(v.pnl/v.decisionCount),maximumSinglePositionContribution:round(v.maximumSinglePositionContribution)})).sort((a,b)=>b.pnl-a.pnl||a.segment.localeCompare(b.segment));}
export function auditPhysicalEventDuplicates(rows:any[]){const m=new Map<string,any[]>();rows.forEach(r=>{const k=r.historicalDerivedMatchKey;if(k)m.set(k,[...(m.get(k)??[]),r])});const groups=[...m].map(([key,x])=>({key,size:x.length,observationIds:x.map(r=>r.observationId),marketFamilies:[...new Set(x.map(r=>r.marketFamilyCanonical))],eventTitles:[...new Set(x.map(r=>r.eventTitle))],classification:new Set(x.map(r=>r.eventTitle)).size===1&&new Set(x.map(r=>r.marketFamilyCanonical)).size>1?"CONFIRMED_DISTINCT_MARKETS":"POSSIBLE_DUPLICATE_EXPOSURE"})).filter(g=>g.size>1);return{derivedGroups:m.size,multiObservationGroups:groups.length,confirmedDistinctMarkets:groups.filter(g=>g.classification==="CONFIRMED_DISTINCT_MARKETS"),possibleDuplicateExposure:groups.filter(g=>g.classification!=="CONFIRMED_DISTINCT_MARKETS"),unresolvedIdentityRows:rows.filter(r=>!r.historicalDerivedMatchKey).map(r=>r.observationId)};}
export function deriveUpdatedDataTrustVerdict(coverage:any,conflicts:number,duplicates:any,dynamicReconciles:boolean){const trusted=(d:any)=>d.HIGH+d.MEDIUM;const allTrusted=[coverage.sport,coverage.league,coverage.marketFamily].every(d=>trusted(d)===coverage.total);const earlyGrowth=allTrusted?"EARLY_GROWTH_EXPLAINED_BY_TRUSTED_SEGMENTS":coverage.sport.LOW+coverage.league.LOW+coverage.marketFamily.LOW>0?"EARLY_GROWTH_DEPENDS_ON_LOW_CONFIDENCE_ATTRIBUTION":"EARLY_GROWTH_UNSUPPORTED";return{earlyGrowthExplanation:earlyGrowth,dataTrust:allTrusted&&!conflicts&&dynamicReconciles?"FULL_HISTORY_DATA_TRUSTED":"DATA_TRUST_UNRESOLVED",modelFreeze:allTrusted&&!conflicts&&dynamicReconciles&&duplicates.possibleDuplicateExposure.length===0?"READY_FOR_FINAL_DOCUMENT_AND_REVIEW":"BLOCKED_PENDING_DATA_REPAIR",evidence:{coverage,conflicts,possibleDuplicateGroups:duplicates.possibleDuplicateExposure.length,dynamicEarlyAnchorReconciles:dynamicReconciles}};}
export function renderAttributionHtml(payload:any){const json=JSON.stringify(payload).replace(/</g,"\\u003c");return`<!doctype html><html><head><meta charset="utf-8"><title>Historical Attribution Repair</title><style>body{font:14px system-ui;max-width:1100px;margin:30px auto}section{border-top:1px solid #ccd;padding:14px}pre{white-space:pre-wrap}</style></head><body><h1>Historical Attribution Repair V1</h1><section><h2>Early versus post-June PnL by sport, league and market family</h2><pre id="segments"></pre></section><section><h2>Top positive and negative physical events</h2><pre id="events"></pre></section><section><h2>Attribution confidence and duplicate-event risk</h2><pre id="quality"></pre></section><section><h2>Updated verdict</h2><pre id="verdict"></pre></section><script id="evidence" type="application/json">${json}</script><script>const d=JSON.parse(document.getElementById('evidence').textContent);for(const k of ['segments','events','quality','verdict'])document.getElementById(k).textContent=JSON.stringify(d[k],null,2)</script></body></html>`;}
export function writeDeterministicManifest(files:Record<string,string>){return{version:"HISTORICAL_ATTRIBUTION_REPAIR_MANIFEST_V1",files:Object.fromEntries(Object.entries(files).sort().map(([n,c])=>[n,createHash("sha256").update(c).digest("hex")]))};}
