import type { ExecutionCandidate } from "./executionWaterfall";
import { classifyResolvedOutcome } from "./roiPnlContract";
import { createStakeReferenceSchedule, isInsideMinskOperationalWindow, minskNightKey, type StakeReferencePolicyId } from "./stakeReferenceSchedule";
import { priceBandOf, type PriceBandMapping } from "./priceBandStakePolicy";
import type { StakeTier } from "./stakeCalibration";

export type NightTerminalReason="EXECUTED_FULL"|"EXECUTED_70"|"EXECUTED_50"|"EXECUTED_30"|"WINDOW_EXCLUDED"|"POSITION_LIMIT"|"EXPOSURE_LIMIT"|"INVALID_SETTLEMENT"|"INVALID_PRICE";
export interface NightArchitectureConfig{referencePolicy:StakeReferencePolicyId;operationWindowOnly:boolean;priceBandMapping:PriceBandMapping;maxOpenPositions:number;maxOpenExposurePct:number;maxAcceptedPerUtcDay:number;initialActiveBankroll:number}
export interface NightAllocationRow{observationId:string;decisionAtIso:string;nightKey:string;entryPrice:number;requestedTier:StakeTier;actualTier:StakeTier;maximumStake:number;stake:number;terminalReason:NightTerminalReason;netPnl:number}
export interface NightArchitectureReplay{config:NightArchitectureConfig;uniqueCandidates:number;executedMatches:number;windowExclusions:number;positionRejects:number;exposureRejects:number;invalidRejects:number;tierDistribution:Record<string,number>;totalStaked:number;wins:number;losses:number;pnl:number;roi:number|null;endingActive:number;maximumTotalDrawdown:number;maximumTotalDrawdownPctOfPeak:number;maximumActiveDrawdown:number;longestLosingStreak:number;maximumPositions:number;maximumExposurePct:number;meanStake:number;maximumStake:number;nightPnl:Record<string,number>;globalFixedComparison:{exceededCurrentThreePct:number;belowCurrentThreePct:number};rows:NightAllocationRow[]}
const round=(x:number)=>Math.round(x*1e8)/1e8;const lower=(t:StakeTier):StakeTier=>t===1?.7:t===.7?.5:t===.5?.3:0;
const rank=(a:ExecutionCandidate,b:ExecutionCandidate)=>b.finalScore-a.finalScore||b.dataCoverage-a.dataCoverage||a.entryPrice-b.entryPrice||Date.parse(a.createdAtIso)-Date.parse(b.createdAtIso)||a.observationId.localeCompare(b.observationId);
export function replayNightStakeArchitecture(candidates:readonly ExecutionCandidate[],config:NightArchitectureConfig):NightArchitectureReplay{
  const ordered=[...candidates].sort((a,b)=>Date.parse(a.decisionAtIso)-Date.parse(b.decisionAtIso)||rank(a,b)),schedule=createStakeReferenceSchedule(config.referencePolicy,config.initialActiveBankroll);
  let free=config.initialActiveBankroll,peak=config.initialActiveBankroll,maxDd=0,maxDdPct=0,wins=0,losses=0,streak=0,longest=0,maxPositions=0,maxExposurePct=0;const open:Array<{c:ExecutionCandidate;stake:number;resolved:number}>=[],acceptedDay=new Map<string,number>(),rows:NightAllocationRow[]=[],nightPnl:Record<string,number>={};
  const settle=(at:number)=>{for(const p of [...open].filter(x=>x.resolved<=at).sort((a,b)=>a.resolved-b.resolved||a.c.observationId.localeCompare(b.c.observationId))){open.splice(open.indexOf(p),1);const win=classifyResolvedOutcome(p.c.row).label==="win",pnl=win?p.stake*(1/p.c.entryPrice-1):-p.stake;free=round(free+p.stake+pnl);const night=minskNightKey(p.resolved);nightPnl[night]=round((nightPnl[night]??0)+pnl);const row=rows.find(x=>x.observationId===p.c.observationId);if(row)row.netPnl=round(pnl);if(win){wins++;streak=0}else{losses++;streak++;longest=Math.max(longest,streak)}const equity=free+open.reduce((s,x)=>s+x.stake,0);peak=Math.max(peak,equity);const dd=peak-equity;maxDd=Math.max(maxDd,dd);maxDdPct=Math.max(maxDdPct,peak?dd/peak*100:0)}};
  for(let i=0;i<ordered.length;){const at=Date.parse(ordered[i].decisionAtIso);settle(at);const batch:ExecutionCandidate[]=[];while(i<ordered.length&&Date.parse(ordered[i].decisionAtIso)===at)batch.push(ordered[i++]);for(const c of batch.sort(rank)){const active=free+open.reduce((s,x)=>s+x.stake,0),maximum=schedule.maximumStake(at,active),band=priceBandOf(c.entryPrice),requested=band?config.priceBandMapping[band]:0,day=new Date(at).toISOString().slice(0,10),nightKey=minskNightKey(at);let tier=requested,reason:NightTerminalReason;
      if(config.operationWindowOnly&&!isInsideMinskOperationalWindow(at)){tier=0;reason="WINDOW_EXCLUDED"}else if(!Number.isFinite(Date.parse(c.resolvedAtIso))||classifyResolvedOutcome(c.row).label==="invalid"){tier=0;reason="INVALID_SETTLEMENT"}else if(!band||requested===0){tier=0;reason="INVALID_PRICE"}else if(open.length>=config.maxOpenPositions){tier=0;reason="POSITION_LIMIT"}else if((acceptedDay.get(day)??0)>=config.maxAcceptedPerUtcDay){tier=0;reason="POSITION_LIMIT"}else{const reference=maximum/.03,exposure=open.reduce((s,x)=>s+x.stake,0);while(tier>0&&exposure+tier*maximum>config.maxOpenExposurePct*reference+1e-9)tier=lower(tier);reason=tier===0?"EXPOSURE_LIMIT":tier===1?"EXECUTED_FULL":tier===.7?"EXECUTED_70":tier===.5?"EXECUTED_50":"EXECUTED_30"}
      const stake=round(tier*maximum);rows.push({observationId:c.observationId,decisionAtIso:c.decisionAtIso,nightKey,entryPrice:c.entryPrice,requestedTier:requested,actualTier:tier,maximumStake:maximum,stake,terminalReason:reason!,netPnl:0});if(tier>0){free=round(free-stake);open.push({c,stake,resolved:Date.parse(c.resolvedAtIso)});acceptedDay.set(day,(acceptedDay.get(day)??0)+1);maxPositions=Math.max(maxPositions,open.length);const reference=maximum/.03;maxExposurePct=Math.max(maxExposurePct,reference?open.reduce((s,x)=>s+x.stake,0)/reference*100:0)}}}
  settle(Infinity);const executed=rows.filter(x=>x.stake>0),totalStaked=round(executed.reduce((s,x)=>s+x.stake,0)),pnl=round(executed.reduce((s,x)=>s+x.netPnl,0)),stakes=executed.map(x=>x.stake);
  return{config,uniqueCandidates:candidates.length,executedMatches:executed.length,windowExclusions:rows.filter(x=>x.terminalReason==="WINDOW_EXCLUDED").length,positionRejects:rows.filter(x=>x.terminalReason==="POSITION_LIMIT").length,exposureRejects:rows.filter(x=>x.terminalReason==="EXPOSURE_LIMIT").length,invalidRejects:rows.filter(x=>x.terminalReason==="INVALID_SETTLEMENT"||x.terminalReason==="INVALID_PRICE").length,tierDistribution:Object.fromEntries([0,.3,.5,.7,1].map(t=>[String(t),rows.filter(x=>x.actualTier===t).length])),totalStaked,wins,losses,pnl,roi:totalStaked?round(pnl/totalStaked*100):null,endingActive:round(free),maximumTotalDrawdown:round(maxDd),maximumTotalDrawdownPctOfPeak:round(maxDdPct),maximumActiveDrawdown:round(maxDd),longestLosingStreak:longest,maximumPositions:maxPositions,maximumExposurePct:round(maxExposurePct),meanStake:stakes.length?round(totalStaked/stakes.length):0,maximumStake:stakes.length?Math.max(...stakes):0,nightPnl,globalFixedComparison:schedule.globalComparisonCounts(),rows};
}
export function bootstrapMinskNights(nightPnl:Record<string,number>,samples=2000,seed=20260715){const values=Object.entries(nightPnl).sort(([a],[b])=>a.localeCompare(b)).map(([,v])=>v);let x=seed|0;const rnd=()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296};const ends:number[]=[],dds:number[]=[];for(let n=0;n<samples;n++){let capital=100,peak=100,dd=0;for(let i=0;i<values.length;i++){capital+=values[Math.floor(rnd()*values.length)]??0;peak=Math.max(peak,capital);dd=Math.max(dd,peak-capital)}ends.push(capital);dds.push(dd)}const p=(a:number[],q:number)=>[...a].sort((a,b)=>a-b)[Math.floor((a.length-1)*q)]??0;return{median:p(ends,.5),p10:p(ends,.1),p90Drawdown:p(dds,.9),probabilityBelowInitial:ends.filter(x=>x<100).length/samples}}
