import type { ExecutionCandidate, WaterfallModelPolicyId } from "./executionWaterfall";
import { classifyResolvedOutcome } from "./roiPnlContract";
import { estimatePastOnlyPnlEdge, type PnlObservation } from "./pnlEdgeEstimator";
import { allocatePnlFirstBatches, type PnlAllocationResult } from "./pnlFirstStakeAllocator";
import type { StakeTier } from "./stakeCalibration";

export interface PnlFirstReplay {
  policyId:"PNL_EB_TIERED_MAX3_V1";model:WaterfallModelPolicyId;candidateMatches:number;executedMatches:number;
  tierDistribution:Record<string,number>;terminalReasons:Record<string,number>;minimumStake:number;medianStake:number;meanStake:number;maximumStake:number;
  totalStaked:number;wins:number;losses:number;grossPnl:number;turnoverRoi:number|null;endingTotalCapital:number;maximumActiveDrawdown:number;
  maximumTotalCapitalDrawdown:number;maximumTotalCapitalDrawdownPctOfPeak:number;longestLosingStreak:number;maximumPositions:number;maximumExposure:number;maximumAcceptedPerDay:number;
  dailyPnl:Record<string,number>;allocationLedger:PnlAllocationResult[];
}
const round=(x:number)=>Math.round(x*1e8)/1e8;
const family=(c:ExecutionCandidate):string|null=>{const d=c.row.diagnostics&&typeof c.row.diagnostics==="object"?c.row.diagnostics as Record<string,unknown>:{};return typeof d.marketFamily==="string"?d.marketFamily:null};
export function pnlStakeTier(edge:number,std:number,evidence:number):StakeTier{if(!(edge>0))return 0;if(evidence<20||std>=.12)return .3;if(edge<.10)return .3;if(edge<.25)return .5;if(edge<.50)return .7;return 1}
export function replayPnlFirst(candidates:readonly ExecutionCandidate[],model:WaterfallModelPolicyId):PnlFirstReplay{
  const history:PnlObservation[]=candidates.map(c=>({observationId:c.observationId,resolvedAtMs:Date.parse(c.resolvedAtIso),win:classifyResolvedOutcome(c.row).label==="win",score:c.finalScore,price:c.entryPrice,coverage:c.dataCoverage,marketFamily:family(c)}));
  const inputs=candidates.map(c=>{const decisionAtMs=Date.parse(c.decisionAtIso),estimate=estimatePastOnlyPnlEdge({observationId:c.observationId,decisionAtMs,score:c.finalScore,price:c.entryPrice,coverage:c.dataCoverage,marketFamily:family(c)},history);const outcome=classifyResolvedOutcome(c.row);return{observationId:c.observationId,decisionAtMs,resolvedAtMs:Date.parse(c.resolvedAtIso),expectedPnlPerDollar:estimate.posteriorMeanExpectedPnl,posteriorEvidenceStrength:estimate.posteriorEvidenceStrength,requestedTier:pnlStakeTier(estimate.posteriorMeanExpectedPnl,estimate.posteriorStdDev,estimate.posteriorEvidenceStrength),finalScore:c.finalScore,dataCoverage:c.dataCoverage,entryPrice:c.entryPrice,createdAtMs:Date.parse(c.createdAtIso),settlementValid:Number.isFinite(Date.parse(c.resolvedAtIso))&&outcome.label!=="invalid"}});
  const allocationLedger=allocatePnlFirstBatches(inputs,50),byId=new Map(candidates.map(c=>[c.observationId,c])),executed=allocationLedger.filter(x=>x.actualStake>0);
  const events=executed.flatMap(x=>[{at:x.decisionAtMs,open:true,x},{at:x.resolvedAtMs,open:false,x}]).sort((a,b)=>a.at-b.at||Number(b.open)-Number(a.open)||a.x.observationId.localeCompare(b.x.observationId));
  let free=50,openStake=0,peakActive=50,peakTotal=100,maxActive=0,maxTotal=0,maxPeak=100,wins=0,losses=0,streak=0,longest=0,maxPositions=0,maxExposure=0;const openIds=new Set<string>(),dailyPnl:Record<string,number>={};
  for(const event of events){const c=byId.get(event.x.observationId)!;if(event.open){free=round(free-event.x.actualStake);openStake=round(openStake+event.x.actualStake);openIds.add(event.x.observationId);maxPositions=Math.max(maxPositions,openIds.size);maxExposure=Math.max(maxExposure,openStake/50*100)}else{const win=classifyResolvedOutcome(c.row).label==="win",pnl=win?event.x.actualStake*(1/c.entryPrice-1):-event.x.actualStake;free=round(free+event.x.actualStake+pnl);openStake=round(openStake-event.x.actualStake);openIds.delete(event.x.observationId);const day=new Date(event.x.resolvedAtMs).toISOString().slice(0,10);dailyPnl[day]=round((dailyPnl[day]??0)+pnl);if(win){wins++;streak=0}else{losses++;streak++;longest=Math.max(longest,streak)}}const active=free+openStake,total=active+50;peakActive=Math.max(peakActive,active);peakTotal=Math.max(peakTotal,total);maxPeak=Math.max(maxPeak,total);maxActive=Math.max(maxActive,peakActive-active);maxTotal=Math.max(maxTotal,peakTotal-total)}
  const stakes=executed.map(x=>x.actualStake).sort((a,b)=>a-b),totalStaked=round(stakes.reduce((a,b)=>a+b,0)),grossPnl=round(Object.values(dailyPnl).reduce((a,b)=>a+b,0));
  return{policyId:"PNL_EB_TIERED_MAX3_V1",model,candidateMatches:candidates.length,executedMatches:executed.length,tierDistribution:Object.fromEntries([0,.3,.5,.7,1].map(t=>[String(t),allocationLedger.filter(x=>x.actualTier===t).length])),terminalReasons:Object.fromEntries([...new Set(allocationLedger.map(x=>x.terminalResult))].sort().map(r=>[r,allocationLedger.filter(x=>x.terminalResult===r).length])),minimumStake:stakes[0]??0,medianStake:stakes.length?stakes[Math.floor((stakes.length-1)/2)]:0,meanStake:stakes.length?round(totalStaked/stakes.length):0,maximumStake:stakes.at(-1)??0,totalStaked,wins,losses,grossPnl,turnoverRoi:totalStaked?round(grossPnl/totalStaked*100):null,endingTotalCapital:round(free+50),maximumActiveDrawdown:round(maxActive),maximumTotalCapitalDrawdown:round(maxTotal),maximumTotalCapitalDrawdownPctOfPeak:round(maxTotal/maxPeak*100),longestLosingStreak:longest,maximumPositions:maxPositions,maximumExposure:round(maxExposure),maximumAcceptedPerDay:Math.max(0,...[...new Set(executed.map(x=>new Date(x.decisionAtMs).toISOString().slice(0,10)))].map(day=>executed.filter(x=>new Date(x.decisionAtMs).toISOString().startsWith(day)).length)),dailyPnl,allocationLedger};
}
