import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { gunzipSync } from "node:zlib";
import type { ExecutionCandidate } from "./executionWaterfall";
import { replayScientificCapitalPolicy, stableHash, type ScientificCapitalReplay } from "./scientificCapitalArchitecture";
import { replayDynamicHarvest } from "./dynamicAwareVault";
import { bootstrapCapitalRisk } from "./scientificCapitalArchitecture";

const round=(n:number)=>Number(n.toFixed(8));
const minsk=(iso:string)=>new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Minsk",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(iso));
const pnl=(r:any)=>r.result==="win"?(1/Number(r.entryPrice)-1):r.result==="loss"?-1:0;
export const canonicalHash=(v:unknown)=>createHash("sha256").update(JSON.stringify(v)).digest("hex");
export function loadFrozenAuditInputs(root:string){const audit=JSON.parse(readFileSync(`${root}/modeling/evidence/2026-07-17-suspicious-growth-temporal-audit-v1/joined_231_observations.json`,"utf8"));const corpus=JSON.parse(gunzipSync(readFileSync(`${root}/modeling/canonical/datasets/2026-07-15-b2f5dfb5963e/generated_signal_pairs_export.json.gz`)).toString("utf8"));return{audit,corpus};}
export function resolveMinskCutoff(date:string){return date;}
export function filterLockedExecutionSequence(rows:any[],cutoff:string){return rows.filter(r=>r.decisionAtIso&&minsk(r.decisionAtIso)>=cutoff).sort((a,b)=>a.executionIndex-b.executionIndex);}
export function freezeOrderedSubset(rows:any[]){return{ids:rows.map(r=>r.observationId),executionOrder:rows.map(r=>r.executionIndex),membershipHash:canonicalHash(rows.map(r=>r.observationId).sort()),executionOrderHash:canonicalHash(rows.map(r=>r.observationId)),replayInputHash:canonicalHash(rows.map(r=>({executionIndex:r.executionIndex,observationId:r.observationId,decisionAtIso:r.decisionAtIso,resolvedAtIso:r.resolvedAtIso,entryPrice:r.entryPrice,result:r.result})))};}
export function runFixedOneUnitControl(rows:any[]){const values=rows.map(pnl),gross=values.reduce((a,b)=>a+b,0);let c=0,peak=0,dd=0,streak=0,long=0;for(const v of values){c+=v;peak=Math.max(peak,c);dd=Math.max(dd,peak-c);streak=v<0?streak+1:0;long=Math.max(long,streak)}const sorted=[...values].sort((a,b)=>a-b);return{count:rows.length,wins:rows.filter(r=>r.result==="win").length,losses:rows.filter(r=>r.result==="loss").length,voidOther:rows.filter(r=>!["win","loss"].includes(r.result)).length,totalStake:rows.length,grossPnl:round(gross),grossRoiPct:round(100*gross/rows.length),meanPnl:round(gross/rows.length),medianPnl:round(sorted.length%2?sorted[(sorted.length-1)/2]:(sorted[sorted.length/2-1]+sorted[sorted.length/2])/2),maximumDrawdown:round(dd),longestLossStreak:long,bestDecision:Math.max(...values),worstDecision:Math.min(...values),breakEvenCostBps:round(10000*gross/rows.length),rolling20Roi:rows.map((_,i)=>i<19?null:round(100*values.slice(i-19,i+1).reduce((a,b)=>a+b,0)/20)),weeklyDecisionDate:Object.entries(rows.reduce((m:any,r:any,i:number)=>{const w=minsk(r.decisionAtIso).slice(0,8)+String(Math.ceil(Number(minsk(r.decisionAtIso).slice(8))/7));m[w]=(m[w]??0)+values[i];return m},{})).map(([week,pnl])=>({week,pnl}))};}
export function applyExecutionCostScenario(control:any,costBps:number){const cost=round(control.totalStake*costBps/10000),net=round(control.grossPnl-cost);return{costBps,costU:cost,netPnl:net,netRoiPct:round(100*net/control.totalStake),drawdownAfterCost:round(control.maximumDrawdown+cost)};}
function candidates(rows:any[],corpus:any[]):ExecutionCandidate[]{const map=new Map(corpus.map(r=>[r.id,r]));return rows.map(r=>({observationId:r.observationId,identity:r.observationId,matchKey:r.observationId,decisionAtIso:r.decisionAtIso,createdAtIso:r.decisionAtIso,resolvedAtIso:r.resolvedAtIso,finalScore:Number(r.signalScore??0),dataCoverage:100,entryPrice:Number(r.entryPrice),row:map.get(r.observationId)} as ExecutionCandidate));}
const capacity={maxOpenPositions:36,maxOpenExposurePct:1,maxAcceptedPerOperatingDay:100,operationWindowOnly:false,initialTotalCapital:50,fixedStake:1} as const;
export function runFixedSafeSuffixReplay(rows:any[],corpus:any[]){return replayScientificCapitalPolicy(candidates(rows,corpus),{family:"ONE_WAY_RATCHETED_CPPI",id:"CPPI_0.4_0.5",alpha:.4,multiplier:.5},{...capacity,stakePolicy:"FIXED_100"});}
export function runDynamicProtectedSuffixReplay(rows:any[],corpus:any[]){return replayDynamicHarvest(candidates(rows,corpus),{family:"DYNAMIC_PRINCIPAL_RECOVERY_VAULT_V2",id:"PRV2_T25_P50_R1_S0.05_C0.1",triggerProfitU:25,principalTargetU:50,principalRecoveryRate:1,postRecoverySkimRate:.05,transferCapPctOfActiveReference:.1});}
export function calculateTemporalStability(rows:any[],control:any){const half=Math.floor(rows.length/2),a=runFixedOneUnitControl(rows.slice(0,half)),b=runFixedOneUnitControl(rows.slice(half));const returns=rows.map(pnl);let seed=20260717;const rnd=()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296};const boots=Array.from({length:10000},()=>returns.reduce((s,_,i)=>s+(returns[Math.floor(rnd()*returns.length)]??0),0)/returns.length).sort((x,y)=>x-y),w=control.wins,n=control.count,p=w/n,z=1.96,d=1+z*z/n,center=(p+z*z/(2*n))/d,margin=z*Math.sqrt((p*(1-p)+z*z/(4*n))/n)/d;return{firstHalf:a,secondHalf:b,rolling20Roi:control.rolling20Roi,rolling40Roi:rows.map((_,i)=>i<39?null:round(100*returns.slice(i-39,i+1).reduce((x,y)=>x+y,0)/40)),top5Contribution:round([...returns].sort((a,b)=>b-a).slice(0,5).reduce((a,b)=>a+b,0)),bootstrapMean95:[round(boots[249]),round(boots[9749])],wilson95:[round(center-margin),round(center+margin)],seed:20260717,resamples:10000};}
export function derivePostJuneFreezeVerdict(control:any,costs:any[],dynamic:any){return{postJuneSignal:control.grossPnl<0?"POST_JUNE_GROSS_NEGATIVE":costs.find(x=>x.costBps===100)?.netPnl<0?"POST_JUNE_FEE_FRAGILE":"POST_JUNE_GROSS_POSITIVE",canonicalScope:"PRE_JUNE8_QUARANTINED_POST_JUNE9_CANONICAL",freezeVerdict:control.grossPnl>0&&dynamic.invalidCapitalStates===0?"POST_JUNE_CANONICAL_BASELINE_FROZEN_REVIEW_REQUIRED":"POST_JUNE_FREEZE_BLOCKED"};}
export function renderPostJuneHtml(p:any){const data=JSON.stringify(p).replace(/</g,"\\u003c");return`<!doctype html><html><head><meta charset="utf-8"><title>Post-June Canonical Baseline</title><style>body{font:14px system-ui;max-width:1050px;margin:30px auto}section{border-top:1px solid #ccd;padding:14px}pre{white-space:pre-wrap}</style></head><body><h1>Post-June Canonical Baseline</h1><section><h2>Fixed-1u, policies, costs and weekly results</h2><pre id="x"></pre></section><script id="e" type="application/json">${data}</script><script>document.getElementById('x').textContent=JSON.stringify(JSON.parse(document.getElementById('e').textContent),null,2)</script></body></html>`;}
export function writeDeterministicManifest(files:Record<string,string>){return{version:"POST_JUNE_CANONICAL_FREEZE_MANIFEST_V1",files:Object.fromEntries(Object.entries(files).sort().map(([n,c])=>[n,createHash("sha256").update(c).digest("hex")]))};}
export const replaySummary=(r:ScientificCapitalReplay)=>{const events=r.ledger.filter(x=>x.stake>0).flatMap(x=>[{at:Date.parse(x.decisionAtIso),d:1},{at:Date.parse(x.resolvedAtIso),d:-1}]).sort((a,b)=>a.at-b.at||a.d-b.d);let open=0,max=0;for(const e of events){open+=e.d;max=Math.max(max,open)}return{executed:r.executedMatches,skipped:r.skippedPositions,totalStaked:r.totalStaked,endingActive:r.endingActive,endingVault:r.endingVault,endingTotal:r.endingTotal,pnl:r.netPnl,maximumFall:r.maximumFallFromTotalPeak,cvar95:bootstrapCapitalRisk(Object.values(r.blockPnl),2,10000,20260717,50).cvar95MaximumFall,maximumConcurrentPositions:max,exposureCeilingViolations:r.curve.filter(x=>x.active&&x.openPrincipal>x.active+1e-8).length,stateHash:stableHash({ledger:r.ledger,curve:r.curve})}};
