import { classifyResolvedOutcome } from "./roiPnlContract";
import type { ExecutionCandidate, ExecutionWaterfallResult, WaterfallModelPolicyId } from "./executionWaterfall";
import { calibratePastOnlyProbability, type CalibrationObservation, type StakeTier } from "./stakeCalibration";
import { runBankrollVaultReplay, type BankrollVaultReplayResult } from "./bankrollVaultReplay";
import type { ExecutableFunnelClassifier } from "./executableFunnelClassifier";
import type { ExportRow } from "./generatedSignalPairsExportContract";

export type OptimizationStakePolicyId = "CONTROL_ACTIVE3_SHRINKING_V1" | "FIXED_CYCLE_MAX3_V1" | "ROBUST_LCB_TIERED_MAX3_V1";
export interface OptimizedReplaySummary { policyId:OptimizationStakePolicyId; model:WaterfallModelPolicyId; uniqueMatchCandidates:number; executedMatches:number; zeroEdgeExclusions:number; capacityReductions:number; capacityRejections:number; stakeTierDistribution:Record<string,number>; minimumStake:number;medianStake:number;meanStake:number;maximumStake:number;totalStaked:number;wins:number;losses:number;grossPnl:number;turnoverRoi:number|null;endingTotalCapital:number;maximumActiveDrawdown:number;maximumTotalCapitalDrawdown:number;maximumTotalCapitalDrawdownPctOfPeak?:number;longestLosingStreak:number;maximumPositions:number;maximumExposure:number;maximumAcceptedPerDay:number;dailyPnl:Record<string,number> }
interface Open { c:ExecutionCandidate; stake:number; tier:StakeTier; resolvedAtMs:number; win:boolean }
const round=(x:number)=>Math.round(x*1e8)/1e8;
const family=(c:ExecutionCandidate):string|null=>{const d=c.row.diagnostics&&typeof c.row.diagnostics==="object"?c.row.diagnostics as Record<string,unknown>:{};return typeof d.marketFamily==="string"?d.marketFamily:null};
function fromControl(result:BankrollVaultReplayResult,model:WaterfallModelPolicyId):OptimizedReplaySummary{const stakes=result.settlementLedger.map(x=>x.stake).sort((a,b)=>a-b),total=stakes.reduce((a,b)=>a+b,0);return{policyId:"CONTROL_ACTIVE3_SHRINKING_V1",model,uniqueMatchCandidates:result.qualifiedSportingMatchGroups,executedMatches:result.selectedObservations,zeroEdgeExclusions:0,capacityReductions:result.reducedBelow3PctStakeOrders,capacityRejections:result.rejectedByReason.OPEN_EXPOSURE_CAP_REJECTED+result.rejectedByReason.CONCURRENT_POSITION_CAP_REJECTED+result.rejectedByReason.DAILY_CAP_REJECTED,stakeTierDistribution:{control:stakes.length},minimumStake:stakes[0]??0,medianStake:stakes.length?stakes[Math.floor((stakes.length-1)/2)]:0,meanStake:stakes.length?total/stakes.length:0,maximumStake:stakes.at(-1)??0,totalStaked:round(total),wins:result.wins,losses:result.losses,grossPnl:result.grossTheoreticalPnl,turnoverRoi:result.grossTheoreticalRoi,endingTotalCapital:result.endingTotalCapital,maximumActiveDrawdown:result.maximumActiveBankrollDrawdown,maximumTotalCapitalDrawdown:result.maximumTotalCapitalDrawdown,longestLosingStreak:result.longestLosingStreak,maximumPositions:result.maximumSimultaneousPositions,maximumExposure:result.maximumOpenExposurePct,maximumAcceptedPerDay:result.maximumAcceptedSignalsInOneUtcDay,dailyPnl:Object.fromEntries(result.settlementLedger.map(x=>[x.resolvedAtIso.slice(0,10),0]).map(([day])=>[day,result.settlementLedger.filter(x=>x.resolvedAtIso.startsWith(day as string)).reduce((s,x)=>s+x.netPnl,0)]))};}
export function replayOptimizedStakePolicy(candidates:readonly ExecutionCandidate[],policyId:Exclude<OptimizationStakePolicyId,"CONTROL_ACTIVE3_SHRINKING_V1">,model:WaterfallModelPolicyId):OptimizedReplaySummary{
  const ordered=[...candidates].sort((a,b)=>Date.parse(a.decisionAtIso)-Date.parse(b.decisionAtIso)||b.finalScore-a.finalScore||b.dataCoverage-a.dataCoverage||a.entryPrice-b.entryPrice||Date.parse(a.createdAtIso)-Date.parse(b.createdAtIso)||a.observationId.localeCompare(b.observationId));
  const history:CalibrationObservation[]=ordered.map(c=>({resolvedAtMs:Date.parse(c.resolvedAtIso),win:classifyResolvedOutcome(c.row).label==="win",score:c.finalScore,price:c.entryPrice,coverage:c.dataCoverage,marketFamily:family(c)}));
  let free=50,vault=50,reference=50,currentDay="",peakActive=50,peakTotal=100,maxActiveDd=0,maxTotalDd=0,maxPos=0,maxExposurePct=0,maxDay=0,wins=0,losses=0,lossStreak=0,longest=0,zero=0,reductions=0,rejections=0;const open:Open[]=[],stakes:number[]=[],tiers:Record<string,number>={"0":0,"0.3":0,"0.5":0,"0.7":0,"1":0},dayAccepted=new Map<string,number>(),dailyPnl:Record<string,number>={};
  const settle=(at:number)=>{for(const p of [...open].filter(x=>x.resolvedAtMs<=at).sort((a,b)=>a.resolvedAtMs-b.resolvedAtMs||a.c.observationId.localeCompare(b.c.observationId))){open.splice(open.indexOf(p),1);const pnl=p.win?p.stake*(1/p.c.entryPrice-1):-p.stake;free=round(free+p.stake+pnl);const day=new Date(p.resolvedAtMs).toISOString().slice(0,10);dailyPnl[day]=round((dailyPnl[day]??0)+pnl);if(p.win){wins++;lossStreak=0}else{losses++;lossStreak++;longest=Math.max(longest,lossStreak)}peakActive=Math.max(peakActive,free+open.reduce((s,x)=>s+x.stake,0));maxActiveDd=Math.max(maxActiveDd,peakActive-(free+open.reduce((s,x)=>s+x.stake,0)));peakTotal=Math.max(peakTotal,free+open.reduce((s,x)=>s+x.stake,0)+vault);maxTotalDd=Math.max(maxTotalDd,peakTotal-(free+open.reduce((s,x)=>s+x.stake,0)+vault));}};
  for(const c of ordered){const at=Date.parse(c.decisionAtIso);settle(at);const day=c.decisionAtIso.slice(0,10);if(day!==currentDay){currentDay=day;reference=free+open.reduce((s,x)=>s+x.stake,0)}const maxStake=.03*reference;const cal=calibratePastOnlyProbability({decisionAtMs:at,score:c.finalScore,price:c.entryPrice,coverage:c.dataCoverage,marketFamily:family(c)},history);let tier:StakeTier=policyId==="FIXED_CYCLE_MAX3_V1"?1:cal.stakeTier;if(tier===0){zero++;tiers["0"]++;continue}const openStake=open.reduce((s,x)=>s+x.stake,0);while(tier>0&&openStake+tier*maxStake>.8*reference+1e-9){tier=tier===1?.7:tier===.7?.5:tier===.5?.3:0;reductions++}if(tier===0||open.length>=30||(dayAccepted.get(day)??0)>=100||tier*maxStake>free+1e-9){rejections++;tiers["0"]++;continue}const stake=round(tier*maxStake);free=round(free-stake);const win=classifyResolvedOutcome(c.row).label==="win";open.push({c,stake,tier,resolvedAtMs:Date.parse(c.resolvedAtIso),win});stakes.push(stake);tiers[String(tier)]++;dayAccepted.set(day,(dayAccepted.get(day)??0)+1);maxDay=Math.max(maxDay,dayAccepted.get(day)!);maxPos=Math.max(maxPos,open.length);maxExposurePct=Math.max(maxExposurePct,reference?open.reduce((s,x)=>s+x.stake,0)/reference*100:0)}settle(Infinity);const totalStake=stakes.reduce((a,b)=>a+b,0),gross=Object.values(dailyPnl).reduce((a,b)=>a+b,0),sorted=[...stakes].sort((a,b)=>a-b);return{policyId,model,uniqueMatchCandidates:candidates.length,executedMatches:stakes.length,zeroEdgeExclusions:zero,capacityReductions:reductions,capacityRejections:rejections,stakeTierDistribution:tiers,minimumStake:sorted[0]??0,medianStake:sorted.length?sorted[Math.floor((sorted.length-1)/2)]:0,meanStake:sorted.length?round(totalStake/sorted.length):0,maximumStake:sorted.at(-1)??0,totalStaked:round(totalStake),wins,losses,grossPnl:round(gross),turnoverRoi:totalStake?round(gross/totalStake*100):null,endingTotalCapital:round(free+vault),maximumActiveDrawdown:round(maxActiveDd),maximumTotalCapitalDrawdown:round(maxTotalDd),longestLosingStreak:longest,maximumPositions:maxPos,maximumExposure:round(maxExposurePct),maximumAcceptedPerDay:maxDay,dailyPnl};}
export function runThreeComparators(rawRows:readonly ExportRow[],classifier:ExecutableFunnelClassifier,waterfall:ExecutionWaterfallResult):OptimizedReplaySummary[]{const control=runBankrollVaultReplay({rawRows,classifier,insuranceBankroll:100,matchIdentityMode:"historical-derived-v1"});return[fromControl(control,"B2_PRICE_FLOOR_030_TIMING_WITHIN_120M"),replayOptimizedStakePolicy(waterfall.executionCandidates,"FIXED_CYCLE_MAX3_V1","B2_PRICE_FLOOR_030_TIMING_WITHIN_120M"),replayOptimizedStakePolicy(waterfall.executionCandidates,"ROBUST_LCB_TIERED_MAX3_V1","B2_PRICE_FLOOR_030_TIMING_WITHIN_120M")];}
