export interface VaultPolicy { id:string; initialActivePct:number; principalRecoveryTrigger:number|null; principalRecoveryAmount:number; highWatermarkSweepPct:number }
export interface VaultLedgerEntry { day:number; kind:"PRINCIPAL_RECOVERY"|"HIGH_WATERMARK_SWEEP"; sweepAmount:number; activeBefore:number; activeAfter:number; vaultBefore:number; vaultAfter:number }
export interface VaultEvaluation { policy:VaultPolicy; ledger:VaultLedgerEntry[]; totalSwept:number; terminalActive:number; terminalVault:number; terminalTotal:number; canonicalPnl:number; maximumTotalDrawdown:number }
export interface OptimizedVaultResult extends VaultEvaluation { bootstrapMedianTerminalCapital:number; bootstrapP10TerminalCapital:number; bootstrapP90MaxDrawdown:number; probabilityEndingBelowInitial:number }
const round=(x:number)=>Math.round(x*1e8)/1e8;
export function evaluateVaultPolicy(dailyRealizedPnl:readonly number[],policy:VaultPolicy):VaultEvaluation{
  let active=100*policy.initialActivePct,vault=100-active,peak=100,dd=0,high=active,recovered=false;const ledger:VaultLedgerEntry[]=[];
  dailyRealizedPnl.forEach((pnl,day)=>{active=round(active+pnl);const total=active+vault;peak=Math.max(peak,total);dd=Math.max(dd,peak-total);
    if(!recovered&&policy.principalRecoveryTrigger!==null&&total>=policy.principalRecoveryTrigger*100){const amount=Math.min(active,policy.principalRecoveryAmount*100);if(amount>0){const ab=active,vb=vault;active=round(active-amount);vault=round(vault+amount);ledger.push({day,kind:"PRINCIPAL_RECOVERY",sweepAmount:amount,activeBefore:ab,activeAfter:active,vaultBefore:vb,vaultAfter:vault})}recovered=true;high=active;}
    if(active>high){const increment=active-high;const amount=round(increment*policy.highWatermarkSweepPct);high=active;if(amount>0){const ab=active,vb=vault;active=round(active-amount);vault=round(vault+amount);ledger.push({day,kind:"HIGH_WATERMARK_SWEEP",sweepAmount:amount,activeBefore:ab,activeAfter:active,vaultBefore:vb,vaultAfter:vault})}}
  });return{policy,ledger,totalSwept:round(ledger.reduce((s,x)=>s+x.sweepAmount,0)),terminalActive:active,terminalVault:vault,terminalTotal:round(active+vault),canonicalPnl:round(dailyRealizedPnl.reduce((a,b)=>a+b,0)),maximumTotalDrawdown:round(dd)};
}
function policies():VaultPolicy[]{const out:VaultPolicy[]=[{id:"NO_VAULT_FULL_COMPOUND",initialActivePct:1,principalRecoveryTrigger:null,principalRecoveryAmount:0,highWatermarkSweepPct:0},{id:"CURRENT_50_50_SWEEP_CONTROL",initialActivePct:.5,principalRecoveryTrigger:null,principalRecoveryAmount:0,highWatermarkSweepPct:.5}];for(const a of [.5,.75,1])for(const t of [1.25,1.5,1.75,2])for(const r of [.25,.5,.75,1])for(const s of [0,.25,.5])out.push({id:`A${a}_T${t}_R${r}_S${s}`,initialActivePct:a,principalRecoveryTrigger:t,principalRecoveryAmount:r,highWatermarkSweepPct:s});return out}
function rng(seed:number){let x=seed|0;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296}}
const percentile=(a:number[],p:number)=>[...a].sort((x,y)=>x-y)[Math.floor((a.length-1)*p)]??0;
export function optimizeVaultPolicies(dailyPnl:readonly number[],samples=2000,seed=20260715):OptimizedVaultResult[]{const valid=policies().map((policy,pi)=>{const terminals:number[]=[],dds:number[]=[];const random=rng(seed+pi);for(let n=0;n<samples;n++){const sample=Array.from({length:dailyPnl.length},()=>dailyPnl[Math.floor(random()*dailyPnl.length)]??0);const e=evaluateVaultPolicy(sample,policy);terminals.push(e.terminalTotal);dds.push(e.maximumTotalDrawdown)}const canonical=evaluateVaultPolicy(dailyPnl,policy);return{...canonical,bootstrapMedianTerminalCapital:percentile(terminals,.5),bootstrapP10TerminalCapital:percentile(terminals,.1),bootstrapP90MaxDrawdown:percentile(dds,.9),probabilityEndingBelowInitial:terminals.filter(x=>x<100).length/samples}}).filter(x=>x.maximumTotalDrawdown<=40.35199895);const best=Math.max(...valid.map(x=>x.bootstrapMedianTerminalCapital));const finalists=valid.filter(x=>x.bootstrapMedianTerminalCapital>=best*.98).sort((a,b)=>b.bootstrapP10TerminalCapital-a.bootstrapP10TerminalCapital||a.bootstrapP90MaxDrawdown-b.bootstrapP90MaxDrawdown||a.policy.id.length-b.policy.id.length||a.policy.id.localeCompare(b.policy.id));const selected=finalists[0];return[selected,...valid.filter(x=>x!==selected).sort((a,b)=>b.bootstrapMedianTerminalCapital-a.bootstrapMedianTerminalCapital||a.policy.id.localeCompare(b.policy.id))];}
