import { PremiumEventCard } from '@/lib/types';

export const premiumEventCards: PremiumEventCard[] = [
  {
    id: '1',
    leagueLabel: 'Politics',
    timeLabel: 'Nov 5, 8:00 PM',
    confidenceBadge: 'High Confidence',
    eventTitle: 'Senate Majority Control',
    positionLabel: 'Position:',
    positionValue: 'REPUBLICANS',
    profitLabel: 'Potential Return:',
    profitValue: '+$420',
    winProbability: 68,
    trustMetrics: [
      { id: 'smart-money', label: 'Smart Money', value: '72% Republican' },
      { id: 'public-whale', label: 'Public vs Whale', value: '68% Aligned' },
      { id: 'ai-score', label: 'PreEventScore AI', value: '8.4/10' }
    ],
    ctaText: 'Unlock Full Analysis',
    priceLabel: '$34.99',
    isActive: true,
  },
  {
    id: '2',
    leagueLabel: 'Crypto',
    timeLabel: 'Jun 30, 11:59 PM',
    confidenceBadge: 'Very High Confidence',
    eventTitle: 'BTC Above $70K by Month End',
    positionLabel: 'Position:',
    positionValue: 'YES',
    profitLabel: 'Potential Return:',
    profitValue: '+$680',
    winProbability: 82,
    trustMetrics: [
      { id: 'smart-money', label: 'Smart Money', value: '91% Bullish' },
      { id: 'public-whale', label: 'Public vs Whale', value: '85% Aligned' },
      { id: 'ai-score', label: 'PreEventScore AI', value: '9.2/10' }
    ],
    ctaText: 'Unlock Full Analysis',
    priceLabel: '$49.99',
    isActive: true,
  },
  {
    id: '3',
    leagueLabel: 'Sports',
    timeLabel: 'Jun 15, 7:30 PM',
    confidenceBadge: 'Medium Confidence',
    eventTitle: 'Lakers vs Celtics Game 6',
    positionLabel: 'Position:',
    positionValue: 'LAKERS -3.5',
    profitLabel: 'Potential Return:',
    profitValue: '+$280',
    winProbability: 55,
    trustMetrics: [
      { id: 'smart-money', label: 'Smart Money', value: '58% Lakers' },
      { id: 'public-whale', label: 'Public vs Whale', value: '52% Aligned' },
      { id: 'ai-score', label: 'PreEventScore AI', value: '6.8/10' }
    ],
    ctaText: 'Unlock Full Analysis',
    priceLabel: '$24.99',
    isActive: true,
  },
  {
    id: '4',
    leagueLabel: 'Economy',
    timeLabel: 'Jul 12, 2:00 PM',
    confidenceBadge: 'High Confidence',
    eventTitle: 'Fed Rate Cut 25bps',
    positionLabel: 'Position:',
    positionValue: 'YES',
    profitLabel: 'Potential Return:',
    profitValue: '+$350',
    winProbability: 71,
    trustMetrics: [
      { id: '1', label: 'Volume', value: '$2.3M', progress: 75 },
      { id: '2', label: 'Liquidity', value: 'High', progress: 90 },
      { id: '3', label: 'Confidence', value: '92%', progress: 92 },
    ],
    ctaText: 'Unlock Full Analysis',
    priceLabel: '$29.99',
    isActive: false,
  },
  {
    id: '1',
    sportIcon: '⚽',
    leagueLabel: 'La Liga',
    timeLabel: '10:00 PM',
    confidenceBadge: 'HIGH CONFIDENCE',
    eventTitle: 'Barcelona vs Real Madrid',
    positionLabel: 'Position',
    positionValue: 'Barcelona',
    profitLabel: 'Profit',
    profitValue: '317%',
    winProbability: 78,
    trustMetrics: [
      { id: 'smart-money', label: 'Smart Money', value: '82%' },
      { id: 'public-whale', label: 'Public vs Whale Money', value: '74%' },
      { id: 'ai-score', label: 'PreEventScore AI', value: '93%' }
    ],
    ctaText: 'Get Pick & Full analysis – 1.99 $',
    priceLabel: '$1.99',
    isActive: true,
  },
  {
    id: '5',
    leagueLabel: 'Crypto',
    timeLabel: 'Jul 8, 4:00 PM',
    confidenceBadge: 'Low Confidence',
    eventTitle: 'ETH ETF Approval This Week',
    positionLabel: 'Position:',
    positionValue: 'NO',
    profitLabel: 'Potential Return:',
    profitValue: '+$180',
    winProbability: 38,
    trustMetrics: [
      { id: 'smart-money', label: 'Smart Money', value: '32% Approval' },
      { id: 'public-whale', label: 'Public vs Whale', value: '45% Aligned' },
      { id: 'ai-score', label: 'PreEventScore AI', value: '4.3/10' }
    ],
    ctaText: 'Unlock Full Analysis',
    priceLabel: '$19.99',
    isActive: false,
  },
  {
    id: '6',
    leagueLabel: 'Politics',
    timeLabel: 'Oct 15, 9:00 PM',
    confidenceBadge: 'Very High Confidence',
    eventTitle: 'Presidential Debate Winner',
    positionLabel: 'Position:',
    positionValue: 'TRUMP',
    profitLabel: 'Potential Return:',
    profitValue: '+$520',
    winProbability: 79,
    trustMetrics: [
      { id: 'smart-money', label: 'Smart Money', value: '84% Trump' },
      { id: 'public-whale', label: 'Public vs Whale', value: '76% Aligned' },
      { id: 'ai-score', label: 'PreEventScore AI', value: '8.9/10' }
    ],
    ctaText: 'Unlock Full Analysis',
    priceLabel: '$44.99',
    isActive: false,
  },
];
