/**
 * CANONICAL_ONE_COMMAND_OFFLINE_MODELING_OPERATOR_V1 — evidence artifact writer.
 *
 * Pure serialization of an already-computed `ReplayRun` into the persisted
 * evidence files the plane + dashboard consume. NO economics are computed here —
 * every number is copied from the `ReplayRun` produced by
 * `replayRunner.ts::runReplay`.
 */
import { createHash } from "node:crypto";
import { readFileSync, readdirSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import type { ReplayRun } from "./types";

export const PLANE_MODULES = [
  "lib/modeling/offline-replay/*.ts",
  "scripts/modeling/offline-replay.ts",
  "scripts/modeling/offline-replay-operator.ts",
  "scripts/modeling/offline-replay-contract-a-attribution.ts",
  "scripts/modeling/offline-replay-contract-a-candidates.ts",
  "scripts/modeling/offline-replay-dashboard.ts",
];

export const PLANE_TESTS = [
  "tests/modeling/offline-replay/contractAFilterSim.ablation.test.ts",
  "tests/modeling/offline-replay/contractAFilterSim.drift.test.ts",
  "tests/modeling/offline-replay/contractAFilterSim.smoke.test.ts",
  "tests/modeling/offline-replay/modelReadyView.contractAFields.test.ts",
  "tests/modeling/offline-replay/policyRegistry.frozen.test.ts",
  "tests/modeling/offline-replay/replayRunner.regression.test.ts",
  "tests/modeling/offline-replay/dashboardModel.test.ts",
  "tests/modeling/offline-replay/deterministicBaselineFreeze.test.ts",
];

function sha256File(p: string): string {
  return createHash("sha256").update(readFileSync(p)).digest("hex");
}

/** deterministic sha256 inventory of the immutable research evidence corpus. */
export function corpusInventory(evidenceDir: string): Record<string, string> {
  const out: Record<string, string> = {};
  if (!existsSync(evidenceDir)) return out;
  for (const f of readdirSync(evidenceDir).sort()) {
    const full = join(evidenceDir, f);
    try {
      out[`research-evidence/${f}`] = sha256File(full);
    } catch {
      /* directory entry — skip */
    }
  }
  return out;
}

export interface ManifestOptions {
  mission: string;
  contractASemanticsSource: string;
}

export function buildManifest(run: ReplayRun, evidenceDir: string, opts: ManifestOptions) {
  // DETERMINISTIC: no timestamps, no wall-clock — regenerating from the same
  // frozen code + pinned corpus must produce byte-identical output.
  return {
    mission: opts.mission,
    window: { from: run.params.from, to: run.params.to, as_of: run.params.as_of },
    economics_basis: run.economics_basis,
    determinism_hash: run.determinism_hash,
    contract_a_semantics_source: opts.contractASemanticsSource,
    replay_requires_production_db_after_materialization: false,
    replay_requires_network: false,
    replay_requires_llm: false,
    replay_requires_new_schema_discovery: false,
    replay_requires_new_helper_script: false,
    field_completeness: run.view_meta.field_completeness ?? null,
    plane_modules: PLANE_MODULES,
    tests: PLANE_TESTS,
    policy_ids: run.params.models,
    overall: run.overall,
    view_meta: run.view_meta,
    sha256: corpusInventory(evidenceDir),
  };
}

/** Compact founder-readable overall table (numbers copied from `run`). */
export function renderFounderTablesMd(run: ReplayRun, contractASemanticsSource: string): string {
  const n = (v: number | null, d = 2) => (v == null ? "—" : v.toFixed(d));
  const rows = run.overall
    .map(
      (r) =>
        `| ${r.MODEL} | ${r.AVAILABLE_PHYSICAL_EVENT_N} | ${r.FILTER_PASS_EVENT_N} | ${r.SIMULATED_BET_N} | ` +
        `${r.TERMINAL_BET_N} | ${r.UNRESOLVED_BET_N} | ${r.WINS} | ${r.LOSSES} | ${n(r.GROSS_PNL_U)} | ` +
        `${n(r.GROSS_ROI_PCT)} | ${n(r.MAX_DD_U)} | ${n(r.WIN_RATE_PCT)} |`,
    )
    .join("\n");
  return `# Offline Policy Replay — founder tables (regenerated by \`npm run modeling:offline-replay:operator\`)

Window \`${run.params.from} .. ${run.params.to}\` · AS-OF \`${run.params.as_of}\` ·
economics **${run.economics_basis}** · determinism_hash \`${run.determinism_hash}\`.

CONTRACT_A_FILTER_SIM_CURRENT semantics source: **${contractASemanticsSource}**

Universe: IDENTITY_N=${run.view_meta.counts.IDENTITY_N} ·
DISTINCT_PHYSICAL_EVENT_N=${run.view_meta.counts.DISTINCT_PHYSICAL_EVENT_N} ·
TERMINAL_LABELED_IDENTITY_N=${run.view_meta.counts.TERMINAL_LABELED_IDENTITY_N} ·
UNRESOLVED_IDENTITY_N=${run.view_meta.counts.UNRESOLVED_IDENTITY_N}

## OVERALL

| MODEL | AVAIL_EVENTS | PASS_EVENTS | BETS | TERMINAL | UNRESOLVED | WINS | LOSSES | PNL_U | ROI_PCT | MAX_DD | WIN_RATE |
|---|--:|--:|--:|--:|--:|--:|--:|--:|--:|--:|--:|
${rows}

Economics are GROSS_BEFORE_FEES · one simulated bet per physical event · UNRESOLVED never enters ROI.
`;
}

export interface WriteEvidenceResult {
  septemberTables: string;
  manifest: string;
  founderTablesMd: string;
}

/** Write SEPTEMBER_TABLES.json + MANIFEST.json + SEPTEMBER_FOUNDER_TABLES.md from `run`. */
export function writeReplayEvidence(
  run: ReplayRun,
  outDir: string,
  researchEvidenceDir: string,
  opts: ManifestOptions,
): WriteEvidenceResult {
  const septemberTables = join(outDir, "SEPTEMBER_TABLES.json");
  const manifest = join(outDir, "MANIFEST.json");
  const founderTablesMd = join(outDir, "SEPTEMBER_FOUNDER_TABLES.md");
  // wall_clock_ms is a timing artifact, not analysis — normalise it so the
  // persisted overall table is byte-stable across regenerations.
  const deterministicRun = { ...run, wall_clock_ms: null };
  writeFileSync(septemberTables, JSON.stringify(deterministicRun));
  writeFileSync(
    manifest,
    JSON.stringify(buildManifest(run, researchEvidenceDir, opts), null, 2),
  );
  writeFileSync(founderTablesMd, renderFounderTablesMd(run, opts.contractASemanticsSource));
  return { septemberTables, manifest, founderTablesMd };
}
