import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  buildDualChronology, calculateResolutionLagAudit, calculateSegmentAttribution, calculateStatisticalStability,
  calculateWindowMetrics, canonicalHash, deriveAuditVerdict, fileHash, loadFrozenContracts, renderAuditHtml,
  runFixedOneUnitSuffixControl, streamJoinLockedObservations, validateJoinedRows, writeDeterministicManifest,
} from "../../../lib/modeling/suspiciousGrowthTemporalAudit";

const root=resolve(process.cwd()), rel="modeling/evidence/2026-07-17-suspicious-growth-temporal-audit-v1", out=resolve(root,rel);mkdirSync(out,{recursive:true});
const frozen=loadFrozenContracts(root), joined=streamJoinLockedObservations(root), gates=validateJoinedRows(joined.rows,231);
const chronology=buildDualChronology(joined.rows), attribution=calculateSegmentAttribution(joined.rows,"2026-05-29","2026-06-07"), lag=calculateResolutionLagAudit(joined.rows);
const suffix8=runFixedOneUnitSuffixControl(joined.rows,"2026-06-08"), suffix9=runFixedOneUnitSuffixControl(joined.rows,"2026-06-09"), statistics=calculateStatisticalStability(joined.rows), verdict=deriveAuditVerdict(gates,suffix9);
const contract={version:"SUSPICIOUS_GROWTH_TEMPORAL_AUDIT_V1",timezone:"Europe/Minsk",seed:20260717,bootstrapResamples:10000,thresholdOptimization:false,initialBankU:50,unitUsd:100,maximumConcurrentPositions:36,activeExposureCeilingPct:100,profiles:["FIXED_SAFE_V1","DYNAMIC_PROTECTED_GROWTH_V1"],suffixes:["2026-06-08","2026-06-09"]};
const lineage={paths:frozen.paths,declaredHashes:{dataset:frozen.contract.dataset.sha256,registry:frozen.contract.registrySha256,identitySet:frozen.contract.identitySet.sha256,executionSequence:frozen.contract.executionSequence.sha256},reproducedCanonicalHashes:{identitySet:canonicalHash([...frozen.identities.identities].sort()),executionSequence:canonicalHash(frozen.sequence.records.map((x:any)=>x.observationId))},byteHashes:Object.fromEntries(Object.entries(frozen.paths).map(([k,p])=>[k,fileHash(resolve(root,p))])),terminalAnchors:{fixedEndingPnlU:51.89997402,dynamicEndingActiveU:119.50804292,dynamicEndingVaultU:52.34252857,dynamicEndingTotalU:171.85057149,dynamicEndingPnlU:121.85057149}};
const growth={settlementFixed:calculateWindowMetrics(joined.rows,"resolvedAtIso","2026-05-29","2026-06-07"),settlementDynamic:calculateWindowMetrics(joined.rows,"resolvedAtIso","2026-05-29","2026-06-07","dynamicRealizedPnl"),postJune8Fixed:calculateWindowMetrics(joined.rows,"resolvedAtIso","2026-06-08"),postJune9Fixed:calculateWindowMetrics(joined.rows,"resolvedAtIso","2026-06-09"),attribution};
const policySensitivity={warning:"Frozen ledger suffix attribution; fresh-bank capital replay is unavailable without reusing forbidden policy internals, so this dimension is explicitly blocked.",suffix8:{fixed:calculateWindowMetrics(joined.rows,"decisionAtIso","2026-06-08"),dynamic:calculateWindowMetrics(joined.rows,"decisionAtIso","2026-06-08",undefined as any,"dynamicRealizedPnl")},suffix9:{fixed:calculateWindowMetrics(joined.rows,"decisionAtIso","2026-06-09"),dynamic:calculateWindowMetrics(joined.rows,"decisionAtIso","2026-06-09",undefined as any,"dynamicRealizedPnl")}};
const quality={...gates,missingIds:joined.missingIds,hashGates:{datasetDeclared:frozen.contract.dataset.sha256==="b2f5dfb5963e036ddb3c2c41a94faff9d7f3eaf08755b9afb9aec7091869be45",registry:frozen.contract.registrySha256==="5ead4f1079920aa61488ce34c17efee1736524f9dd5a95c747f2dcb487d1bf34",identity:lineage.reproducedCanonicalHashes.identitySet==="99f22a9bb8db0a2ff7bddd8e72f87a097fdb136f1a242a300ccb0e8740d0fcca",sequence:lineage.reproducedCanonicalHashes.executionSequence==="5457240a539e5db189c1b23659678f157b322928105909a5812ce318a9d6b036"}};
quality.pass=quality.pass&&Object.values(quality.hashGates).every(Boolean);
const csv=(rows:any[])=>{const keys=[...new Set(rows.flatMap(Object.keys))];const q=(v:any)=>`"${String(v??"").replaceAll('"','""')}"`;return keys.join(",")+"\n"+rows.map(r=>keys.map(k=>q(typeof r[k]==="object"?JSON.stringify(r[k]):r[k])).join(",")).join("\n")+"\n"};
const files:Record<string,string>={};const add=(name:string,value:any)=>files[name]=typeof value==="string"?value:JSON.stringify(value,null,2)+"\n";
add("audit_contract.json",contract);add("source_lineage.json",lineage);add("joined_231_observations.json",joined.rows);add("joined_231_observations.csv",csv(joined.rows));add("data_quality_gates.json",quality);add("dual_chronology_daily.json",chronology);add("dual_chronology_daily.csv",csv([...chronology.settlement.map(x=>({chronology:"settlement",...x})),...chronology.decision.map(x=>({chronology:"decision",...x}))]));add("growth_window_attribution.json",growth);add("growth_window_attribution.csv",csv(attribution));add("resolution_lag_audit.json",lag);add("post_june_suffix_replay.json",{signalQuality:{suffix8,suffix9},policySensitivity});add("statistical_stability.json",statistics);add("verdict.json",verdict);
const ru=`# Аудит подозрительного роста и временной устойчивости\n\nДата: 2026-07-17. Часовой пояс: Europe/Minsk. Пороговые значения модели не изменялись.\n\n## Итог\n\n- Data trust: **${verdict.dataTrust}**.\n- Temporal stability: **${verdict.temporalStability}**.\n- Freeze/review: **${verdict.freezeReview}**.\n- Join: ${quality.represented}/231, missing IDs: ${joined.missingIds.length}, duplicates: ${quality.duplicateObservationIds.length}.\n- Покрытие sport/league/market family: отсутствует соответственно у ${quality.missingAttribution.sport}/${quality.missingAttribution.league}/${quality.missingAttribution.marketFamily} строк; значения не выдумывались.\n\n## Рост 29 мая — 7 июня по времени settlement\n\nFixed: ${growth.settlementFixed.count} решений, stake ${growth.settlementFixed.stake}u, PnL ${growth.settlementFixed.pnl}u, ROI ${growth.settlementFixed.roiPct}%. Dynamic: PnL ${growth.settlementDynamic.pnl}u.\n\n## Чистый fixed-1u suffix\n\n8 июня+: ${suffix8.count} решений, PnL ${suffix8.grossPnl}u, ROI ${suffix8.grossRoiPct}%, max DD ${suffix8.maximumDrawdown}u, break-even ${suffix8.breakEvenExecutionCostBps} bps.\n\n9 июня+: ${suffix9.count} решений, PnL ${suffix9.grossPnl}u, ROI ${suffix9.grossRoiPct}%, max DD ${suffix9.maximumDrawdown}u, break-even ${suffix9.breakEvenExecutionCostBps} bps.\n\nИнтервалы неопределённости не исправляют ошибки исходных данных. Из-за неполной source-backed атрибуции финальная заморозка заблокирована.\n`;
add("SUSPICIOUS_GROWTH_TEMPORAL_AUDIT_RU.md",ru);add("suspicious_growth_temporal_audit.html",renderAuditHtml({chronology,suffix:{suffix8,suffix9},attribution,lag,gates:quality,verdict}));
for(const [name,content] of Object.entries(files))writeFileSync(resolve(out,name),content);const manifest=writeDeterministicManifest(files);writeFileSync(resolve(out,"manifest.json"),JSON.stringify(manifest,null,2)+"\n");
console.log(JSON.stringify({output:rel,joined:joined.rows.length,missing:joined.missingIds.length,verdict},null,2));
