import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { BANKROLL_PROFILE_REGISTRY } from "../../../lib/modeling/bankrollProfileRegistry";
import { buildCanonicalModelHandoff, DATASET_DIR, DATASET_SHA, EVIDENCE_DIR, EXECUTION_SHA, IDENTITY_SHA, json, REGISTRY_SHA, sha, verifyCanonicalModelHandoff } from "../../../lib/modeling/canonicalModelHandoff";

const DOCS: Record<string, string> = {
  "CANONICAL_MODEL_ARCHITECTURE_V1.md": `# Canonical Model Architecture V1\n\nПакет фиксирует модель B2_PRICE_FLOOR_030_TIMING_WITHIN_120M как селектор уже рассчитанных score-полей. **The approved selector consumes already-produced score fields. Score production itself is not reimplemented by this handoff package.** Формула score не изобретается.\n\nКонтракт: активный score threshold, исключение eSports, price floor 0.30, окно ≤120m, identity normalization, sporting-match grouping, ranking/tie-breaks и one execution per event определены executable source и тестами в SOURCE_TEST_EVIDENCE_MAP_V1.md. Порядок: детерминированный entry; settlement по времени с same-time batching; Minsk cycles; capacity 36 и exposure fail-closed.\n\nFixed: FIXED_1U + ONE_WAY_RATCHETED_CPPI CPPI_0.4_0.5 (alpha=0.4, multiplier=0.5). Dynamic: DYNAMIC_ACTIVE_3PCT + DYNAMIC_PRINCIPAL_RECOVERY_VAULT_V2 PRV2_T25_P50_R1_S0.05_C0.1. Active, Vault, freeActive/openPrincipal и carried state — капитал-состояние. Скрещивание Fixed stake с Dynamic Vault и Dynamic stake с Fixed Vault запрещено.\n`,
  "DATASET_FREEZE_AND_REPLAY_CONTRACT_V1.md": `# Dataset Freeze and Replay Contract V1\n\nCorpus — BYTE_FROZEN_SNAPSHOT: 49,400 rows, SHA ${DATASET_SHA}. Historical export provenance PARTIAL: source generated_signal_pairs; resolved_at IS NOT NULL; known upper rule resolved_at <= exportCutoffResolvedAt; keyset resolved_at,id DESC; no pre-export dedup; downstream identity condition_id+token_id; UTC. Exact invocation, lower boundary, export-start cutoff and DB revision are not proven.\n\n## DECLARED QUERY BOUNDARY\nLower boundary: not declared. Upper value: not recovered.\n\n## OBSERVED VALUE RANGE IN FROZEN BYTES\nObserved minima/maxima are inventory facts only and never declared boundaries. T−90 selects latest snapshot at/before event start minus 90 minutes.\n\nIdentity set proves 231 memberships via lexicographic serialization. Execution sequence proves immutable ledger array order, including entry/settlement chronology, Minsk cycles, state carry, capacity/exposure, stake and skip reasons. **The lexicographically serialized identity set is not the replay order. Downstream execution must not sort observation IDs lexicographically.**\n\nVerify: npx tsx scripts/modeling/strategies/freeze-canonical-model-handoff.ts --verify\n`,
  "SOURCE_TEST_EVIDENCE_MAP_V1.md": `# Source / Test / Evidence Map V1\n\n| Contract | Source / export | Test | Evidence | Coverage |\n|---|---|---|---|---|\n| signal/filter, threshold, eSports, floor, timing | lib/modeling/postCutoffModelMembership.ts | tests/modeling/postCutoffModelMembership.test.ts | ${EVIDENCE_DIR}/manifest.json | DIRECT UNIT |\n| identity normalization/grouping/ranking/tie-breaks | lib/modeling/eventGroupSelection.ts | tests/modeling/eventGroupSelection.test.ts | ${EVIDENCE_DIR}/fixed_profile_ledger.json | REGRESSION |\n| stake and capital state | lib/modeling/scientificCapitalArchitecture.ts | tests/modeling/scientificCapitalArchitecture.test.ts | ${EVIDENCE_DIR}/*_profile_curve.json | HISTORICAL EVIDENCE |\n| Fixed/Dynamic profiles | lib/modeling/bankrollProfileRegistry.ts | tests/modeling/bankrollProfileRegistry.test.ts | ${EVIDENCE_DIR}/manifest.json | DETERMINISTIC HASH |\n| identity/execution split | lib/modeling/canonicalModelHandoff.ts | tests/modeling/canonicalModelHandoff.test.ts | locked_*.json | DETERMINISTIC HASH |\n\nFive pre-existing unchanged repository failures are KNOWN BASELINE GAP. Source export provenance is PARTIAL. Score production is outside this package. Exact dependency hashes are in source_hash_inventory.json; test names and classifications are in test_evidence_matrix.json.\n`,
  "DOWNSTREAM_INTEGRATION_HANDOFF_V1.md": `# Downstream Integration Handoff V1\n\nTarget contour must verify manifest, corpus, registry, identity-set and execution-sequence hashes; require an explicit approved profile ID; reuse canonical executable modules; preserve filter, entry, settlement, batching and state transitions; fail closed on mismatch.\n\nForbidden: lexicographic execution sorting; recreating filters from Markdown; copied formulas without parity tests; LLM parameter selection; Dynamic with Fixed Vault; Fixed with Dynamic Vault; different dataset SHA; claims of reproducible historical re-export. Acceptance gates: hashes PASS, paths resolve, parity tests PASS, profile pairing approved, immutable sequence retained, no runtime integration until founder Gate 2A.\n`,
  "FOUNDER_README_RU.md": `# Founder README — Canonical Model Handoff V1\n\nМодель отбирает уже оценённые сигналы B2: применяет утверждённые фильтры, группирует один sporting event и исполняет один победивший вариант. Frozen corpus — точные 49,400 строк; байты проверяются SHA. Исходный исторический SQL восстановлен частично, поэтому повторный export не объявляется воспроизводимым.\n\n231 identities — состав когорты, а chronological replay order — отдельный порядок ledgers; сортировать UUID для исполнения нельзя. Fixed Safe ставит 1u и односторонне защищает капитал Vault. Dynamic Protected ставит 3% Active по Minsk-cycle reference и переносит прибыль в Vault по recovery/skim policy; Active и Vault несут состояние между циклами.\n\nSource/tests/data находятся в lib/modeling, tests/modeling, ${DATASET_DIR}, ${EVIDENCE_DIR}. Нельзя менять signal, dataset/registry SHA, параметры, historical results или смешивать stake/Vault профили. Следующий шаг — только downstream integration после Gate 2A.\n`,
};

export function freeze(root = process.cwd()) {
  const out = path.join(root, "modeling/canonical/model-handoff-v1"); mkdirSync(out, { recursive: true });
  const built = buildCanonicalModelHandoff(root);
  const write = (name: string, value: unknown) => writeFileSync(path.join(out, name), typeof value === "string" ? value : json(value));
  write("locked_signal_identity_set.json", built.identitySet); write("locked_execution_sequence.json", built.executionSequence);
  const datasetRoot = path.join(root, DATASET_DIR);
  writeFileSync(path.join(datasetRoot, "locked_signal_identity_set.json"), json(built.identitySet));
  writeFileSync(path.join(datasetRoot, "locked_execution_sequence.json"), json(built.executionSequence));
  const datasetFreezeManifestPath = path.join(datasetRoot, "dataset_freeze_manifest.json");
  const datasetFreezeManifest = JSON.parse(readFileSync(datasetFreezeManifestPath, "utf8"));
  delete datasetFreezeManifest.lockedSequenceCount; delete datasetFreezeManifest.lockedSequenceSha256;
  datasetFreezeManifest.identitySet = { count: 231, artifact: "locked_signal_identity_set.json", sha256: IDENTITY_SHA, serialization: built.identitySet.serialization };
  datasetFreezeManifest.executionSequence = { count: 231, artifact: "locked_execution_sequence.json", sha256: EXECUTION_SHA, serialization: built.executionSequence.serialization, sourceLedgers: built.executionSequence.sourceLedgers };
  writeFileSync(datasetFreezeManifestPath, json(datasetFreezeManifest));
  const datasetPackageManifestPath = path.join(datasetRoot, "manifest.json");
  const datasetPackageManifest = JSON.parse(readFileSync(datasetPackageManifestPath, "utf8"));
  datasetPackageManifest.artifacts["dataset_freeze_manifest.json"] = sha(readFileSync(datasetFreezeManifestPath));
  datasetPackageManifest.artifacts["locked_signal_identity_set.json"] = sha(readFileSync(path.join(datasetRoot, "locked_signal_identity_set.json")));
  datasetPackageManifest.artifacts["locked_execution_sequence.json"] = sha(readFileSync(path.join(datasetRoot, "locked_execution_sequence.json")));
  datasetPackageManifest.datasetFreezeManifestSha256 = datasetPackageManifest.artifacts["dataset_freeze_manifest.json"];
  datasetPackageManifest.identitySetSha256 = IDENTITY_SHA; datasetPackageManifest.executionSequenceSha256 = EXECUTION_SHA;
  datasetPackageManifest.legacyLockedSignalSequenceCompatibility = "locked_signal_sequence.json retained; membership-only, not execution order";
  const manifestPayload = { ...datasetPackageManifest }; delete manifestPayload.packageManifestSha256;
  datasetPackageManifest.packageManifestSha256 = sha(json(manifestPayload));
  writeFileSync(datasetPackageManifestPath, json(datasetPackageManifest));
  for (const [name, body] of Object.entries(DOCS)) write(name, body);
  const contract = { version: "CANONICAL_MODEL_CONTRACT_V1", signal: "B2_PRICE_FLOOR_030_TIMING_WITHIN_120M", dataset: { artifact: `../datasets/2026-07-15-b2f5dfb5963e/generated_signal_pairs_export.json.gz`, sha256: DATASET_SHA }, registrySha256: REGISTRY_SHA, identitySet: { count: 231, artifact: "locked_signal_identity_set.json", sha256: IDENTITY_SHA, serialization: built.identitySet.serialization }, executionSequence: { count: 231, artifact: "locked_execution_sequence.json", sha256: EXECUTION_SHA, serialization: built.executionSequence.serialization, sourceLedgers: built.executionSequence.sourceLedgers }, approvedProfiles: BANKROLL_PROFILE_REGISTRY.profiles, forbiddenProfilePairings: [{ stake: "FIXED_1U", vault: "PRV2_T25_P50_R1_S0.05_C0.1" }, { stake: "DYNAMIC_ACTIVE_3PCT", vault: "CPPI_0.4_0.5" }], exportProvenance: { corpusAuthority: "BYTE_FROZEN_SNAPSHOT", queryContractStatus: "PARTIAL", historicalSourceReExportReproducible: false, declaredQueryBoundary: { lower: null, upper: null }, observedValueRangeIsNotDeclaredBoundary: true } };
  write("canonical_model_contract.json", contract);
  const fixedCurve = JSON.parse(readFileSync(path.join(root, EVIDENCE_DIR, "fixed_profile_curve.json"), "utf8")), dynamicCurve = JSON.parse(readFileSync(path.join(root, EVIDENCE_DIR, "dynamic_profile_curve.json"), "utf8"));
  const event = (row: any, sequenceIndex: number) => ({ sequenceIndex, observationId: row.observationId, decisionAtIso: row.decisionAtIso, resolvedAtIso: row.resolvedAtIso, stake: row.stake, entryPrice: row.entryPrice, result: row.result, netPnl: row.netPnl, terminalReason: row.terminalReason });
  const chart = { version: "CANONICAL_CHART_DATA_V1", lineage: "IMMUTABLE_COMMITTED_CURVES_AND_LEDGER_ARRAY_ORDER_ONLY", fixedCapitalCurve: fixedCurve, dynamicCapitalCurve: dynamicCurve, dynamicActiveVaultCurve: dynamicCurve, fixedSettledEvents: built.fixed.map(event), dynamicSettledEvents: built.dynamic.map(event) }; write("chart_data.json", chart);
  const testMatrix = [{ contract: "corpus/registry hashes", test: "canonicalModelHandoff.test.ts", coverage: "DETERMINISTIC HASH" }, { contract: "identity/execution separation", test: "canonicalModelHandoff.test.ts", coverage: "DIRECT UNIT" }, { contract: "chart lineage/offline renderer", test: "canonicalModelHandoff.test.ts", coverage: "REGRESSION" }]; write("test_evidence_matrix.json", testMatrix);
  const dependencies = ["lib/modeling/canonicalModelHandoff.ts", "lib/modeling/bankrollProfileRegistry.ts", "lib/modeling/postCutoffModelMembership.ts", "lib/modeling/eventGroupSelection.ts", "lib/modeling/scientificCapitalArchitecture.ts", "tests/modeling/canonicalModelHandoff.test.ts", "tests/modeling/bankrollProfileRegistry.test.ts", `${DATASET_DIR}/dataset_freeze_manifest.json`, `${DATASET_DIR}/generated_signal_pairs_export.json.gz`, `${EVIDENCE_DIR}/fixed_profile_ledger.json`, `${EVIDENCE_DIR}/dynamic_profile_ledger.json`, `${EVIDENCE_DIR}/fixed_profile_curve.json`, `${EVIDENCE_DIR}/dynamic_profile_curve.json`, ...Object.keys(DOCS).map((x) => `modeling/canonical/model-handoff-v1/${x}`)];
  const category = (p: string) => p.startsWith("tests/") ? "TEST" : p.endsWith(".md") ? "DOCUMENTATION" : p.includes("evidence/") ? "HISTORICAL_EVIDENCE" : p.includes("datasets/") ? "IMMUTABLE_INPUT" : "EXECUTABLE_SOURCE";
  write("source_hash_inventory.json", dependencies.map((p) => ({ path: p, classification: category(p), sha256: sha(readFileSync(path.join(root, p))) })));
  const plotlyShim = `const Plotly={newPlot:(id,traces,layout)=>{const e=document.getElementById(id),w=900,h=280,svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 '+w+' '+h);svg.innerHTML='<rect width="900" height="280" fill="#fff"/><text x="12" y="22">'+layout.title+'</text>';traces.forEach((t,j)=>{const a=t.y.filter(Number.isFinite),lo=Math.min(...a),hi=Math.max(...a),p=t.y.map((v,i)=>(20+i*(860/Math.max(1,t.y.length-1)))+','+(250-(v-lo)*210/Math.max(1e-9,hi-lo))).join(' '),n=document.createElementNS(svg.namespaceURI,'polyline');n.setAttribute('points',p);n.setAttribute('fill','none');n.setAttribute('stroke',['#2563eb','#dc2626','#16a34a'][j%3]);n.setAttribute('stroke-width','2');svg.appendChild(n)});e.appendChild(svg)}};`;
  const html = `<!doctype html><meta charset="utf-8"><title>Canonical Model Evidence V1</title><style>body{font:14px system-ui;margin:24px;color:#172033}.chart{max-width:1100px;border:1px solid #ccd6e0;margin:16px 0}code{font-size:12px}</style><h1>Canonical Model Offline Plotly Evidence V1</h1><p>Historical evidence only. Initial reference: 50u. Development/confirmation boundary is shown only where committed evidence supports it.</p><p>Identity membership (${IDENTITY_SHA}) is distinct from immutable replay order (${EXECUTION_SHA}); execution IDs are never lexicographically reordered.</p><p>Sources: chart_data.json; ${EVIDENCE_DIR}/fixed_profile_{curve,ledger}.json and dynamic_profile_{curve,ledger}.json.</p>${[1,2,3,4,5].map(i=>`<div id="c${i}" class="chart"></div>`).join("")}<script>${plotlyShim}</script><script>const d=${JSON.stringify(chart)};Plotly.newPlot('c1',[{y:d.fixedCapitalCurve.map(x=>x.total)},{y:d.dynamicCapitalCurve.map(x=>x.total)}],{title:'1. Fixed Safe Total versus Dynamic Protected Total'});Plotly.newPlot('c2',[{y:d.dynamicActiveVaultCurve.map(x=>x.active)},{y:d.dynamicActiveVaultCurve.map(x=>x.vault)},{y:d.dynamicActiveVaultCurve.map(x=>x.total)}],{title:'2. Dynamic Active, Vault and Total'});Plotly.newPlot('c3',[{y:d.fixedCapitalCurve.map(x=>x.fallFromTotalPeak)},{y:d.dynamicCapitalCurve.map(x=>x.fallFromTotalPeak)}],{title:'3. Fixed versus Dynamic drawdown from Total peak'});Plotly.newPlot('c4',[{y:d.fixedSettledEvents.map(x=>x.stake)},{y:d.fixedSettledEvents.map(x=>x.netPnl)}],{title:'4. Fixed settled stake and PnL sequence'});Plotly.newPlot('c5',[{y:d.dynamicSettledEvents.map(x=>x.stake)},{y:d.dynamicSettledEvents.map(x=>x.netPnl)}],{title:'5. Dynamic settled stake and PnL sequence'});</script>`; write("offline_plotly_dashboard.html", html);
  const manifestFiles = ["locked_signal_identity_set.json", "locked_execution_sequence.json", "canonical_model_contract.json", "source_hash_inventory.json", "test_evidence_matrix.json", "chart_data.json", "offline_plotly_dashboard.html", ...Object.keys(DOCS)]; write("manifest.json", { version: "CANONICAL_MODEL_HANDOFF_MANIFEST_V1", files: Object.fromEntries(manifestFiles.map((f) => [f, sha(readFileSync(path.join(out, f)))])) });
  return verifyCanonicalModelHandoff(root, out);
}

if (require.main === module) { const result = process.argv.includes("--verify") ? verifyCanonicalModelHandoff(process.cwd(), path.join(process.cwd(), "modeling/canonical/model-handoff-v1")) : freeze(); console.log(JSON.stringify(result)); }
