#!/usr/bin/env -S node --import tsx
import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import type { ExportRow } from "../../../lib/modeling/generatedSignalPairsExportContract";
import { buildExecutionWaterfall, type ExecutionCandidate } from "../../../lib/modeling/executionWaterfall";
import { loadExecutableFunnelClassifier } from "../../../lib/modeling/executableFunnelClassifier";
import { replayNightStakeArchitecture } from "../../../lib/modeling/nightStakeArchitecture";
import { buildPrincipalRecoveryStageA, type PrincipalRecoveryPolicy } from "../../../lib/modeling/dynamicPrincipalRecoveryVault";
import { replayDynamicHarvest, type DynamicHarvestReplay } from "../../../lib/modeling/dynamicAwareVault";
import { carryBoundaryState, chronologicalTailMean95, selectDevelopmentPolicy, stateAtBoundary, STATE_CARRYING_LABEL } from "../../../lib/modeling/dynamicVaultStateCarrying";
import { bootstrapCapitalRisk, replayScientificCapitalPolicy, stableHash, type ScientificCapitalReplay } from "../../../lib/modeling/scientificCapitalArchitecture";
import { LOCKED_CPPI_04_05 } from "../../../lib/modeling/lockedFixedVsDynamicProfiles";
import { minskNightKey } from "../../../lib/modeling/stakeReferenceSchedule";

const DATASET_SHA = "b2f5dfb5963e036ddb3c2c41a94faff9d7f3eaf08755b9afb9aec7091869be45";
const IDS_SHA = "99f22a9bb8db0a2ff7bddd8e72f87a097fdb136f1a242a300ccb0e8740d0fcca";
const PRIMARY_ID = "PRV2_T25_P50_R1_S0.05_C0.1";
const BLOCKS = ["2026-05-25","2026-05-26","2026-05-28","2026-05-29","2026-05-30","2026-05-31","2026-06-01","2026-06-02","2026-06-03","2026-06-04","2026-06-05","2026-06-06","2026-06-07","2026-06-08","2026-06-09","2026-06-10","2026-06-11","2026-06-12","2026-06-13","2026-06-14","2026-06-15","2026-06-16","2026-06-17","2026-06-18","2026-06-19","2026-06-20","2026-06-21","2026-06-22","2026-07-05","2026-07-06","2026-07-07","2026-07-09","2026-07-10","2026-07-11"] as const;
const DEVELOPMENT = BLOCKS.slice(0, 23), CONFIRMATION = BLOCKS.slice(23);
const BOUNDARY_MS = Date.parse("2026-06-18T15:00:00.000Z");
const ALL100 = { "0.30_0.40":1,"0.40_0.50":1,"0.50_0.60":1,"0.60_0.70":1,"0.70_1.00":1 } as const;
const sha = (value: string | Buffer) => createHash("sha256").update(value).digest("hex");
const round = (value: number) => Math.round(value * 1e8) / 1e8;
const serialize = (value: unknown) => `${JSON.stringify(value, null, 2)}\n`;
function write(root: string, name: string, value: unknown) { const text = typeof value === "string" ? value : serialize(value); writeFileSync(path.join(root, name), text); return sha(text); }
function assertClose(actual: number, expected: number, label: string) { if (Math.abs(actual - expected) > 1e-8) throw new Error(`CONTROL_OR_CANDIDATE_REPRODUCTION_MISMATCH ${label}: ${actual} != ${expected}`); }

function pointTime(atIso: string) { return atIso === "INITIAL" ? -Infinity : atIso === "FINAL" ? Infinity : Date.parse(atIso); }
function dynamicWindow(replay: DynamicHarvestReplay, blocks: readonly string[], startMs: number, endMs: number, starting: ReturnType<typeof stateAtBoundary> | null, ending: ReturnType<typeof stateAtBoundary> | null) {
  const blockSet = new Set(blocks), intended = replay.ledger.filter(row => blockSet.has(minskNightKey(Date.parse(row.decisionAtIso)))), executed = intended.filter(row => row.stake > 0);
  const settled = replay.ledger.filter(row => row.stake > 0 && Date.parse(row.resolvedAtIso) >= startMs && Date.parse(row.resolvedAtIso) < endMs);
  const curve = replay.curve.filter(point => pointTime(point.atIso) >= startMs && pointTime(point.atIso) < endMs);
  const transfers = replay.transfers.filter(row => Date.parse(row.atIso) >= startMs && Date.parse(row.atIso) < endMs);
  const starts = starting ?? { freeActive:50, openPrincipal:0, active:50, vault:0, total:50 };
  const finalPoint = replay.curve.at(-1)!;
  const ends = ending ?? { freeActive:finalPoint.freeActive, openPrincipal:finalPoint.openPrincipal, active:finalPoint.active, vault:finalPoint.vault, total:finalPoint.total };
  const totalStaked = round(executed.reduce((sum, row) => sum + row.stake, 0)), pnl = round(settled.reduce((sum, row) => sum + row.netPnl, 0));
  const cycles = new Map<string, number>(); for (const transfer of transfers) cycles.set(transfer.cycleId, round((cycles.get(transfer.cycleId) ?? 0) + transfer.amount));
  return { startingActive:starts.active, startingVault:starts.vault, startingTotal:starts.total, endingFreeActive:ends.freeActive, endingOpenPrincipal:ends.openPrincipal, endingActive:ends.active, endingVault:ends.vault, endingTotal:ends.total, intended:intended.length, executed:executed.length, skipped:intended.length-executed.length, skipReasons:Object.fromEntries(["POSITION_LIMIT","EXPOSURE_LIMIT","INSUFFICIENT_ACTIVE_CAPACITY"].map(reason=>[reason,intended.filter(row=>row.terminalReason===reason).length])), wins:settled.filter(row=>row.result==="win").length, losses:settled.filter(row=>row.result==="loss").length, totalStaked, pnl, roi:totalStaked?round(pnl/totalStaked*100):0, minimumTotal:Math.min(starts.total,...curve.map(point=>point.total)), maximumTotalFall:Math.max(0,...curve.map(point=>point.fallFromTotalPeak)), maximumActiveFall:Math.max(0,...curve.map(point=>point.fallFromActivePeak)), cvar95MaximumFall:round(chronologicalTailMean95(curve.map(point=>point.fallFromTotalPeak))), probabilityBelowInitial:curve.length?round(curve.filter(point=>point.total<50).length/curve.length):0, maximumConcurrentPositions:Math.max(starting?.openPositionIds.length??0,...curve.map(point=>replay.ledger.filter(row=>row.stake>0&&Date.parse(row.decisionAtIso)<=pointTime(point.atIso)&&Date.parse(row.resolvedAtIso)>pointTime(point.atIso)).length)), maximumLockedPrincipal:Math.max(starts.openPrincipal,...curve.map(point=>point.openPrincipal)), vaultTransferCount:transfers.length, firstTransfer:transfers[0]?.atIso??null, lastTransfer:transfers.at(-1)?.atIso??null, totalTransferred:round(transfers.reduce((sum,row)=>sum+row.amount,0)), largestTransfer:Math.max(0,...transfers.map(row=>row.amount)), maximumCycleTransfer:Math.max(0,...cycles.values()), blockStartStateHash:stableHash(starts), blockEndStateHash:stableHash(ends), capitalCurveHash:stableHash(curve), vaultLedgerHash:stableHash(transfers), executionHash:stableHash(intended), capitalValid:curve.every(point=>point.freeActive>=-1e-8&&point.active>=-1e-8&&point.vault>=-1e-8&&point.total>=-1e-8) };
}
function fullDynamic(replay: DynamicHarvestReplay) { const risk=bootstrapCapitalRisk(Object.values(replay.blockPnl),2,20000,20260716,50); return { intended:replay.intendedSignals,executed:replay.executed,skipped:replay.skipped,skipReasons:replay.skipReasons,wins:replay.wins,losses:replay.losses,totalStaked:replay.totalStaked,pnl:replay.pnl,roi:replay.roi,endingFreeActive:replay.endingFreeActive,endingOpenPrincipal:replay.endingOpenPrincipal,endingActive:replay.endingActive,endingVault:replay.endingVault,endingTotal:replay.endingTotal,minimumTotal:replay.minimumTotal,maximumTotalFall:replay.maximumFallFromTotalPeak,maximumActiveFall:replay.maximumFallFromActivePeak,cvar95MaximumFall:risk.cvar95MaximumFall,probabilityBelowInitial:risk.probabilityBelowInitial,maximumConcurrentPositions:replay.maximumConcurrentPositions,maximumLockedPrincipal:replay.maximumLockedPrincipal,vaultTransferCount:replay.transfers.length,firstTransfer:replay.transfers[0]?.atIso??null,lastTransfer:replay.transfers.at(-1)?.atIso??null,totalTransferred:round(replay.transfers.reduce((sum,row)=>sum+row.amount,0)),largestTransfer:Math.max(0,...replay.transfers.map(row=>row.amount)),maximumCycleTransfer:Math.max(0,...Object.values(Object.groupBy(replay.transfers,row=>row.cycleId)).map(rows=>rows!.reduce((sum,row)=>sum+row.amount,0))),blockStartStateHash:stableHash({active:50,vault:0,total:50}),blockEndStateHash:stableHash(replay.curve.at(-1)),capitalCurveHash:replay.capitalCurveHash,vaultLedgerHash:replay.transferLedgerHash,executionHash:replay.executionLedgerHash,capitalValid:replay.invalidCapitalStates===0 }; }
function fixedFull(replay: ScientificCapitalReplay) { const risk=bootstrapCapitalRisk(Object.values(replay.blockPnl),2,20000,20260716,50); return { pnl:replay.netPnl,maximumTotalFall:replay.maximumFallFromTotalPeak,cvar95MaximumFall:risk.cvar95MaximumFall,endingActive:replay.endingActive,endingVault:replay.endingVault,endingTotal:replay.endingTotal,executed:replay.executedMatches,skipped:replay.skippedPositions }; }
function resetDiagnostic(candidates: readonly ExecutionCandidate[], policy: PrincipalRecoveryPolicy) { const rows=BLOCKS.map(block=>replayDynamicHarvest(candidates.filter(row=>minskNightKey(Date.parse(row.decisionAtIso))===block),policy)); return { label:STATE_CARRYING_LABEL.reset,selectionEligible:false,triggerReachedBlocks:rows.filter(row=>row.transfers.length>0).length,vaultTransfers:rows.reduce((sum,row)=>sum+row.transfers.length,0),endingVault:round(rows.reduce((sum,row)=>sum+row.endingVault,0)) }; }
function dashboard(evidence: unknown) { const data=JSON.stringify(evidence).replace(/</g,"\\u003c"); return `<!doctype html><meta charset=utf-8><title>State-carrying Dynamic Vault validation</title><style>body{font:14px system-ui;margin:24px}section{border-top:1px solid #ccd6df;padding:16px 0}pre{max-height:620px;overflow:auto;background:#f5f7f9;padding:12px}</style><h1>Dynamic Vault State-Carrying Validation</h1><p><b>historical state-carrying pseudo-OOS — not true forward validation</b></p>${["Continuous Total curves","Continuous Active/Vault curves","Development/confirmation boundary","Block 23→24 carried state","Vault-transfer timeline","Protected vs Dynamic No Vault","Protected vs Fixed Safe","Maximum-fall curves","Reset vs state carry","Development PnL ranking","Confirmation incremental results"].map(title=>`<section><h2>${title}</h2><p>Rendered from embedded immutable evidence; no policy logic is recalculated.</p></section>`).join("")}<pre id=e></pre><script id=machine-evidence type=application/json>${data}</script><script>e.textContent=document.getElementById('machine-evidence').textContent</script>`; }

export function runStateCarryingValidation(input: string, root: string) {
  const raw=readFileSync(input); if(sha(raw)!==DATASET_SHA) throw new Error("frozen dataset hash mismatch"); mkdirSync(root,{recursive:true});
  const waterfall=buildExecutionWaterfall(JSON.parse(raw.toString()) as ExportRow[],loadExecutableFunnelClassifier(),"B2_PRICE_FLOOR_030_TIMING_WITHIN_120M"), old=replayNightStakeArchitecture(waterfall.executionCandidates,{referencePolicy:"MINSK_NIGHT_FIXED_MAX3_V1",operationWindowOnly:false,priceBandMapping:ALL100,maxOpenPositions:36,maxOpenExposurePct:1,maxAcceptedPerUtcDay:100,initialActiveBankroll:50}), ids=old.rows.filter(row=>row.stake>0).map(row=>row.observationId).sort();
  if(ids.length!==231||stableHash(ids)!==IDS_SHA) throw new Error("locked 231-ID sequence mismatch"); const locked=new Set(ids),candidates=waterfall.executionCandidates.filter(row=>locked.has(row.observationId));
  const registry=buildPrincipalRecoveryStageA(); if(registry.length!==24) throw new Error("candidate registry changed"); const registryHash=stableHash(registry);
  const controlReplay=replayDynamicHarvest(candidates,{family:"NO_VAULT",id:"DYNAMIC_NO_VAULT"}), controlFull=fullDynamic(controlReplay);
  assertClose(controlFull.pnl,169.32412195,"dynamic pnl"); assertClose(controlFull.maximumTotalFall,33.96564534,"dynamic fall"); assertClose(controlFull.cvar95MaximumFall,43.85905932,"dynamic cvar"); if(controlFull.executed!==230||controlFull.skipped!==1) throw new Error("CONTROL_OR_CANDIDATE_REPRODUCTION_MISMATCH dynamic counts");
  const fixedReplay=replayScientificCapitalPolicy(candidates,LOCKED_CPPI_04_05,{maxOpenPositions:36,maxOpenExposurePct:1,maxAcceptedPerOperatingDay:100,operationWindowOnly:false,stakePolicy:"FIXED_100",initialTotalCapital:50,fixedStake:1}), fixed= fixedFull(fixedReplay);
  assertClose(fixed.pnl,51.89997402,"fixed pnl"); assertClose(fixed.maximumTotalFall,6.43150453,"fixed fall"); assertClose(fixed.cvar95MaximumFall,9.92765355,"fixed cvar"); assertClose(fixed.endingVault,40.75998961,"fixed vault");
  const rows=registry.map(policy=>{const replay=replayDynamicHarvest(candidates,policy), boundary=stateAtBoundary(replay,BOUNDARY_MS,policy.transferCapPctOfActiveReference), carried=carryBoundaryState(boundary), development=dynamicWindow(replay,DEVELOPMENT,-Infinity,BOUNDARY_MS,null,boundary),confirmation=dynamicWindow(replay,CONFIRMATION,BOUNDARY_MS,Infinity,boundary,null),full=fullDynamic(replay);return{policy,replay,boundary:carried,development,confirmation,full};});
  const primary=rows.find(row=>row.policy.id===PRIMARY_ID)!; assertClose(primary.full.pnl,121.85057149,"primary pnl"); assertClose(primary.full.endingActive,119.50804292,"primary active"); assertClose(primary.full.endingVault,52.34252857,"primary vault"); assertClose(primary.full.endingTotal,171.85057149,"primary total"); assertClose(primary.full.maximumTotalFall,19.99816041,"primary fall"); assertClose(primary.full.cvar95MaximumFall,25.69447488,"primary cvar");
  const controlBoundary=stateAtBoundary(controlReplay,BOUNDARY_MS,0), controlDevelopment=dynamicWindow(controlReplay,DEVELOPMENT,-Infinity,BOUNDARY_MS,null,controlBoundary), controlConfirmation=dynamicWindow(controlReplay,CONFIRMATION,BOUNDARY_MS,Infinity,controlBoundary,null);
  const fixedDevelopmentPnl=round(DEVELOPMENT.reduce((sum,block)=>sum+(fixedReplay.blockPnl[block]??0),0));
  const selection=selectDevelopmentPolicy(rows.map(row=>({id:row.policy.id,pnl:row.development.pnl,maximumFall:row.development.maximumTotalFall,cvar95:row.development.cvar95MaximumFall,endingVault:row.development.endingVault,additionalSkips:row.development.skipped-controlDevelopment.skipped,capitalValid:row.development.capitalValid,noFutureLeakage:true})),{fixedSafePnl:fixedDevelopmentPnl,dynamicMaximumFall:controlDevelopment.maximumTotalFall,dynamicCvar95:controlDevelopment.cvar95MaximumFall});
  const winner=selection.winner?rows.find(row=>row.policy.id===selection.winner!.id)!:null, validated=winner!==null&&winner.full.pnl>=60&&winner.full.pnl>fixed.pnl&&winner.full.maximumTotalFall<controlFull.maximumTotalFall&&winner.full.cvar95MaximumFall<controlFull.cvar95MaximumFall&&winner.full.endingVault>=25&&winner.confirmation.pnl>0&&winner.full.capitalValid;
  const reset=resetDiagnostic(candidates,primary.policy), carryDiagnostic={triggerReachedBlocks:new Set(primary.replay.transfers.map(row=>row.cycleId)).size,vaultTransfers:primary.replay.transfers.length,endingVault:primary.full.endingVault};
  const stateSchema={version:"DYNAMIC_VAULT_CARRIED_STATE_V1",fields:["freeActive","openPrincipal","active","vault","total","totalHighWater","activeHighWater","peakProfit","principalRecoveryProgress","currentStakeReference","remainingTransferAllowance","openPositionIds"]};
  const result={version:"DYNAMIC_VAULT_STATE_CARRYING_VALIDATION_V1",status:validated?"STATE_CARRYING_VALIDATION_SUPPORTS_PROTECTED_DYNAMIC_CANDIDATE":"STATE_CARRYING_VALIDATION_DOES_NOT_SUPPORT_PROTECTED_DYNAMIC_CANDIDATE",labels:STATE_CARRYING_LABEL,datasetSha256:DATASET_SHA,inputExecutionIdsSha256:IDS_SHA,candidateRegistryHash:registryHash,stateSchemaHash:stableHash(stateSchema),candidateCount:registry.length,methodology:{developmentBlocks:DEVELOPMENT,confirmationBlocks:CONFIRMATION,selectionUsesConfirmation:false,confirmationLabel:STATE_CARRYING_LABEL.confirmation,bootstrap:"STATEFUL_BOOTSTRAP_NOT_APPLICABLE_UNDER_CURRENT_ORACLE",chronologicalTailMetric:"mean of worst 5% observed running maximum-fall points"},comparators:{dynamicNoVault:{development:controlDevelopment,confirmation:controlConfirmation,full:controlFull},fixedSafe:{developmentPnl:fixedDevelopmentPnl,full:fixed}},developmentResults:rows.map(({policy,development})=>({policy,development,eligible:selection.evaluated.find(item=>item.row.id===policy.id)?.eligible??false})),developmentWinner:winner?.policy??null,confirmation:winner?.confirmation??null,fullContinuous:winner?.full??null,primaryCandidate:{policy:primary.policy,development:primary.development,confirmation:primary.confirmation,full:primary.full},blockBoundary:winner?.boundary??primary.boundary,resetVersusStateCarry:{reset,stateCarry:carryDiagnostic},frontier:{DEVELOPMENT_PNL_MAX_PROTECTED:winner?.policy.id??null,STATE_CARRYING_MIN_TAIL_RISK:[...rows].sort((a,b)=>a.full.cvar95MaximumFall-b.full.cvar95MaximumFall)[0].policy.id,STATE_CARRYING_MAX_PROTECTION:[...rows].sort((a,b)=>b.full.endingVault-a.full.endingVault)[0].policy.id,STATE_CARRYING_PARETO_FRONTIER:rows.filter(row=>!rows.some(other=>other.policy.id!==row.policy.id&&other.full.pnl>=row.full.pnl&&other.full.maximumTotalFall<=row.full.maximumTotalFall&&other.full.endingVault>=row.full.endingVault&&(other.full.pnl>row.full.pnl||other.full.maximumTotalFall<row.full.maximumTotalFall||other.full.endingVault>row.full.endingVault))).map(row=>row.policy.id)},decision:{validated,developmentWinnerEqualsPrimary:winner?.policy.id===PRIMARY_ID,additionalSkips:winner?winner.full.skipped-controlFull.skipped:null}};
  const hashes:Record<string,string>={}; hashes.stateSchema=write(root,"state_schema.json",stateSchema); hashes.development=write(root,"development_results.json",result.developmentResults); hashes.confirmation=write(root,"confirmation_results.json",result.confirmation); hashes.full=write(root,"full_continuous_results.json",{winner:result.fullContinuous,primary:result.primaryCandidate.full,comparators:result.comparators}); hashes.boundary=write(root,"block_boundary_state_ledger.json",result.blockBoundary); hashes.diagnostic=write(root,"reset_versus_state_carry_diagnostic.json",result.resetVersusStateCarry); hashes.selection=write(root,"development_selection.json",{winner:result.developmentWinner,evaluated:selection.evaluated,frontier:result.frontier}); hashes.curves=write(root,"capital_curves.json",{winner:winner?.replay.curve??null,primary:primary.replay.curve,dynamicNoVault:controlReplay.curve,fixedSafe:fixedReplay.curve}); hashes.transfers=write(root,"vault_transfer_ledger.json",winner?.replay.transfers??[]); hashes.decision=write(root,"founder_decision_packet.json",result);
  const report=`# State-carrying Dynamic Vault validation\n\nСтарый block-local reset возвращал Active к 50u и Vault к 0u, поэтому не мог проверить накопительный Principal Recovery Vault. Новый контракт выполняет один непрерывный replay: капитал, Vault, high-water marks, открытые позиции, transfer progress и stake reference переходят через границы Minsk blocks.\n\nDevelopment winner: ${winner?.policy.id??"none"}. Confirmation: ${winner?.confirmation.pnl??"n/a"}u. Full PnL: ${winner?.full.pnl??"n/a"}u. Vault: ${winner?.full.endingVault??"n/a"}u. Status: ${result.status}.\n\nЭто historical state-carrying pseudo-OOS, not true forward validation. Frozen bootstrap не применяется к state-dependent path; приведены exact chronological metrics.\n`;
  hashes.report=write(root,"founder_report_ru.md",report); hashes.dashboard=write(root,"dashboard.html",dashboard(result)); hashes.verification=write(root,"VERIFICATION.md",`# Verification\n\n- Dataset SHA: ${DATASET_SHA}\n- 231-ID SHA: ${IDS_SHA}\n- Registry: 24 unchanged policies\n- Continuous replay reproductions: PASS\n- Block 23 end hash equals block 24 start hash: ${result.blockBoundary.block23EndHash===result.blockBoundary.block24StartHash}\n`); hashes.methodology=write(root,"methodology.md",`# Methodology correction\n\nOne continuous chronological replay is partitioned only for reporting. No settlement, capital, Vault, open-position, high-water, transfer, or stake-reference state resets at the development/confirmation boundary. ${STATE_CARRYING_LABEL.reset} is diagnostic and is not selection-eligible.\n`);
  const manifest={datasetSha256:DATASET_SHA,inputExecutionIdsSha256:IDS_SHA,candidateRegistryHash:registryHash,stateSchemaHash:stableHash(stateSchema),artifactHashes:hashes,decisionStatus:result.status,manifestSha256:stableHash({hashes,status:result.status})}; write(root,"manifest.json",manifest); return {result,manifest};
}

if (require.main===module) { const [input,root]=process.argv.slice(2); if(!input||!root) throw new Error("usage: run-dynamic-vault-state-carrying-validation <input> <output>"); console.log(JSON.stringify(runStateCarryingValidation(input,root),null,2)); }
