#!/usr/bin/env -S node --import tsx
import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { buildExecutionWaterfall, type WaterfallModelPolicyId } from "../../../lib/modeling/executionWaterfall";
import { loadExecutableFunnelClassifier } from "../../../lib/modeling/executableFunnelClassifier";
import { runThreeComparators, replayOptimizedStakePolicy } from "../../../lib/modeling/stakeVaultOptimization";
import { replayPnlFirst } from "../../../lib/modeling/pnlFirstReplay";
import { attributeFixedMaximumCapacity } from "../../../lib/modeling/capacityRejectionAttribution";
import { evaluateVaultPolicy, optimizeVaultPolicies, vaultParetoFrontier } from "../../../lib/modeling/vaultPolicyOptimizer";
import { DEFAULT_FOUNDER_RISK_CONFIG } from "../../../lib/modeling/founderRiskConfig";
import type { ExportRow } from "../../../lib/modeling/generatedSignalPairsExportContract";

const sha=(s:string)=>createHash("sha256").update(s).digest("hex");
const json=(v:unknown)=>`${JSON.stringify(v,null,2)}\n`;
const write=(root:string,name:string,value:unknown)=>{const content=json(value);writeFileSync(path.join(root,name),content);return sha(content)};
function bootstrap(daily:Record<string,number>,samples=2000,seed=20260715){const values=Object.entries(daily).sort(([a],[b])=>a.localeCompare(b)).map(([,v])=>v);let x=seed|0;const random=()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296};const terminal:number[]=[],drawdown:number[]=[];for(let n=0;n<samples;n++){let capital=100,peak=100,dd=0;for(let i=0;i<values.length;i++){capital+=values[Math.floor(random()*values.length)]??0;peak=Math.max(peak,capital);dd=Math.max(dd,peak-capital)}terminal.push(capital);drawdown.push(dd)}const p=(a:number[],q:number)=>[...a].sort((a,b)=>a-b)[Math.floor((a.length-1)*q)]??0;return{medianEndingCapital:p(terminal,.5),p10EndingCapital:p(terminal,.1),p90MaximumDrawdown:p(drawdown,.9),probabilityEndingBelowInitial:terminal.filter(v=>v<100).length/samples}}
export function runStakeVaultOptimization(input:string,outputRoot:string):Record<string,unknown>{
  const raw=readFileSync(input,"utf8"),rows=JSON.parse(raw) as ExportRow[],classifier=loadExecutableFunnelClassifier();mkdirSync(outputRoot,{recursive:true});
  const primary=buildExecutionWaterfall(rows,classifier),capacity=attributeFixedMaximumCapacity(primary.executionCandidates),legacy=runThreeComparators(rows,classifier,primary),pnl=replayPnlFirst(primary.executionCandidates,"B2_PRICE_FLOOR_030_TIMING_WITHIN_120M");
  const stakePolicies=[...legacy.map(x=>({...x,bootstrap:bootstrap(x.dailyPnl)})),{...pnl,bootstrap:bootstrap(pnl.dailyPnl)}];
  const eligible=stakePolicies.filter(x=>x.maximumTotalCapitalDrawdown<=40.35199895);const bestMedian=Math.max(...eligible.map(x=>x.bootstrap.medianEndingCapital));const selectedStake=[...eligible.filter(x=>x.bootstrap.medianEndingCapital>=bestMedian*.98)].sort((a,b)=>b.grossPnl-a.grossPnl||b.bootstrap.p10EndingCapital-a.bootstrap.p10EndingCapital||a.bootstrap.p90MaximumDrawdown-b.bootstrap.p90MaximumDrawdown||String(a.policyId).localeCompare(String(b.policyId)))[0];
  const daily=Object.entries(selectedStake.dailyPnl).sort(([a],[b])=>a.localeCompare(b)).map(([,v])=>v),vaultGrid=optimizeVaultPolicies(daily,2000,20260715),selectedVault=vaultGrid[0],pareto=vaultParetoFrontier(vaultGrid);
  const models:WaterfallModelPolicyId[]=["B2_PRICE_FLOOR_030_TIMING_WITHIN_120M","B2_TIMING_WITHIN_120M","B2_PRICE_FLOOR_030"];
  const comparisons=models.map(model=>{const wf=model===models[0]?primary:buildExecutionWaterfall(rows,classifier,model);const replay=selectedStake.policyId==="PNL_EB_TIERED_MAX3_V1"?replayPnlFirst(wf.executionCandidates,model):replayOptimizedStakePolicy(wf.executionCandidates,selectedStake.policyId==="ROBUST_LCB_TIERED_MAX3_V1"?"ROBUST_LCB_TIERED_MAX3_V1":"FIXED_CYCLE_MAX3_V1",model);const modelDaily=Object.entries(replay.dailyPnl).sort(([a],[b])=>a.localeCompare(b)).map(([,v])=>v),eligibleVault=optimizeVaultPolicies(modelDaily,2000,20260715),vault=eligibleVault.find(x=>x.policy.id===selectedVault.policy.id)??{...evaluateVaultPolicy(modelDaily,selectedVault.policy),...bootstrap(replay.dailyPnl)};return{model,latestBaseCohort:wf.baseModelRows,t90Cohort:wf.t90QualifiedRows,defensibleUniqueMatches:wf.derivedSportingMatchGroups,recoveredMatches:wf.identityRecoveryAudit.safelyRecoveredRows,replay,selectedStakePolicy:selectedStake.policyId,selectedVaultPolicy:selectedVault.policy.id,vault}});
  const identity={...primary.identityRecoveryAudit,finalDefensibleUniqueMatches:primary.derivedSportingMatchGroups,exactRemainingReason:"NO_UNIQUE_EXACT_SLUG_START_LINK"};
  const capacitySummary={...capacity,rows:undefined,reasonDetails:Object.fromEntries([...new Set(capacity.rows.map(x=>x.terminalResult))].sort().map(reason=>{const found=capacity.rows.filter(x=>x.terminalResult===reason);return[reason,{count:found.length,wins:found.filter(x=>x.counterfactualFlatOneUnitPnl>0).length,losses:found.filter(x=>x.counterfactualFlatOneUnitPnl<0).length,flatOneUnitCounterfactualPnl:found.reduce((s,x)=>s+x.counterfactualFlatOneUnitPnl,0),fixedMaximumCounterfactualPnl:found.reduce((s,x)=>s+x.counterfactualFixedMaximumPnl,0),entryPrices:found.map(x=>x.entryPrice),decisionTimes:found.map(x=>x.decisionAtIso),overlapWindows:found.map(x=>x.overlapPositions),representativeExamples:found.slice(0,5).map(x=>x.observationId)}]}))};
  const artifactHashes:Record<string,string>={};artifactHashes["historical_identity_recovery.json"]=write(outputRoot,"historical_identity_recovery.json",identity);artifactHashes["capacity_rejection_attribution.json"]=write(outputRoot,"capacity_rejection_attribution.json",capacity);artifactHashes["stake_policy_comparison.json"]=write(outputRoot,"stake_policy_comparison.json",stakePolicies);artifactHashes["selected_stake_replay.json"]=write(outputRoot,"selected_stake_replay.json",selectedStake);artifactHashes["vault_policy_grid.json"]=write(outputRoot,"vault_policy_grid.json",vaultGrid);artifactHashes["vault_pareto_frontier.json"]=write(outputRoot,"vault_pareto_frontier.json",pareto);artifactHashes["selected_vault_replay.json"]=write(outputRoot,"selected_vault_replay.json",selectedVault);artifactHashes["primary_shadow_comparison.json"]=write(outputRoot,"primary_shadow_comparison.json",comparisons);
  const classifierRaw=readFileSync("modeling/model_registry/executable_funnel_classifier.json","utf8"),selectionHash=sha(json({model:models[0],stake:selectedStake.policyId,vault:selectedVault.policy.id,risk:DEFAULT_FOUNDER_RISK_CONFIG}));
  const manifestBase={modelPolicyVersion:models[0],historicalMatchIdentityVersion:identity.version,stakePolicyVersion:selectedStake.policyId,vaultPolicyVersion:selectedVault.policy.id,riskPolicyVersion:"FOUNDER_RISK_MAX3_TIERED_V1",settlementContractVersion:"BANKROLL_VAULT_SETTLEMENT_CONTRACT_V1",datasetSha256:sha(raw),classifierSha256:sha(classifierRaw),selectionHash,replayJsonSha256:artifactHashes["selected_stake_replay.json"],artifactHashes,bootstrap:{samples:2000,seed:20260715},founderRiskConfig:DEFAULT_FOUNDER_RISK_CONFIG};const manifestSha256=sha(json(manifestBase));const manifest={...manifestBase,manifestSha256};write(outputRoot,"freeze_candidate_manifest.json",manifest);
  return{identity,capacitySummary,stakePolicies,selectedStake,vaultGrid,pareto,selectedVault,comparisons,manifest};
}
if(require.main===module){const input=process.argv[2],out=process.argv[3];if(!input||!out)throw new Error("usage: run-stake-vault-optimization <input.json> <output-root>");console.log(JSON.stringify(runStakeVaultOptimization(input,out),null,2));}
