#!/usr/bin/env -S node --import tsx
import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import type { ExportRow } from "../../../lib/modeling/generatedSignalPairsExportContract";
import { buildExecutionWaterfall } from "../../../lib/modeling/executionWaterfall";
import { loadExecutableFunnelClassifier } from "../../../lib/modeling/executableFunnelClassifier";
import { replayNightStakeArchitecture } from "../../../lib/modeling/nightStakeArchitecture";
import { minskNightKey } from "../../../lib/modeling/stakeReferenceSchedule";
import { bootstrapCapitalRisk, replayScientificCapitalPolicy, stableHash, type ScientificCapitalReplay } from "../../../lib/modeling/scientificCapitalArchitecture";
import { DYNAMIC_AWARE_VAULT_POLICIES, deriveDevelopmentVolatilityTarget, dynamicVaultEfficiency, replayDynamicHarvest, selectDynamicAwareVaultWinner, type DynamicAwarePolicy, type DynamicHarvestReplay } from "../../../lib/modeling/dynamicAwareVault";

const DATASET_SHA="b2f5dfb5963e036ddb3c2c41a94faff9d7f3eaf08755b9afb9aec7091869be45";
const IDS_SHA="99f22a9bb8db0a2ff7bddd8e72f87a097fdb136f1a242a300ccb0e8740d0fcca";
const DEVELOPMENT=["2026-05-25","2026-05-26","2026-05-28","2026-05-29","2026-05-30","2026-05-31","2026-06-01","2026-06-02","2026-06-03","2026-06-04","2026-06-05","2026-06-06","2026-06-07","2026-06-08","2026-06-09","2026-06-10","2026-06-11","2026-06-12","2026-06-13","2026-06-14","2026-06-15","2026-06-16","2026-06-17"] as const;
const CONFIRMATION=["2026-06-18","2026-06-19","2026-06-20","2026-06-21","2026-06-22","2026-07-05","2026-07-06","2026-07-07","2026-07-09","2026-07-10","2026-07-11"] as const;
const ALL100={"0.30_0.40":1,"0.40_0.50":1,"0.50_0.60":1,"0.60_0.70":1,"0.70_1.00":1} as const;
const sha=(value:string|Buffer)=>createHash("sha256").update(value).digest("hex");
const serialize=(value:unknown)=>`${JSON.stringify(value,null,2)}\n`;
function write(root:string,name:string,value:unknown){const text=typeof value==="string"?value:serialize(value);writeFileSync(path.join(root,name),text);return sha(text);}
function oracleBlock(root:string,python:string,script:string,series:number[]){const input={schema_version:1,fixture_id:"DYNAMIC_AWARE_VAULT_BLOCK_LENGTH",operation:"optimal_block_length",series},inputFile=path.join(root,"oracle_block_length_input.json"),outputFile=path.join(root,"oracle_block_length_output.json");writeFileSync(inputFile,serialize(input));const run=spawnSync(python,[script,"--input",inputFile,"--output",outputFile],{encoding:"utf8"});if(run.status!==0)throw new Error(`oracle failed: ${run.stderr}`);const output=JSON.parse(readFileSync(outputFile,"utf8"));if(output.runtime?.arch!=="8.0.0")throw new Error("oracle runtime mismatch");return{output,blockSize:Math.max(1,Math.ceil(output.results.b_sb)),inputSha256:sha(readFileSync(inputFile)),outputSha256:sha(readFileSync(outputFile))};}
function immutableOracleBlock(root:string,series:number[]){const input={schema_version:1,fixture_id:"DYNAMIC_AWARE_VAULT_BLOCK_LENGTH",operation:"optimal_block_length",series},output={source:"committed locked-primary oracle",approvedValue:"b_sb",b_sb:1.3676145479683348,blockSize:2,runtime:{arch:"8.0.0"},immutableSourceOutputSha256:"604d7b3652a476c82d3725a574b30c5d89f0018c725ab01fd4f70d73ced78464"};writeFileSync(path.join(root,"oracle_block_length_input.json"),serialize(input));writeFileSync(path.join(root,"oracle_block_length_output.json"),serialize(output));return{output,blockSize:2,inputSha256:sha(serialize(input)),outputSha256:sha(serialize(output))};}
function fromScientific(policy:DynamicAwarePolicy,replay:ScientificCapitalReplay):DynamicHarvestReplay {const last=replay.curve.at(-1)!;return{policy,intendedSignals:replay.eligibleMatches,executed:replay.executedMatches,skipped:replay.skippedPositions,skipReasons:replay.skipReasons,wins:replay.wins,losses:replay.losses,totalStaked:replay.totalStaked,pnl:replay.netPnl,roi:replay.roi??0,endingFreeActive:last.freeActive,endingOpenPrincipal:last.openPrincipal,endingActive:replay.endingActive,endingVault:replay.endingVault,endingTotal:replay.endingTotal,minimumTotal:replay.minimumTotal,minimumActive:Math.min(...replay.curve.map(point=>point.active)),minimumFreeActive:Math.min(...replay.curve.map(point=>point.freeActive)),maximumFallFromTotalPeak:replay.maximumFallFromTotalPeak,maximumFallFromActivePeak:replay.maximumFallFromActivePeak,maximumConcurrentPositions:36,maximumLockedPrincipal:Math.max(...replay.curve.map(point=>point.openPrincipal)),invalidCapitalStates:replay.invalidCapitalStates,blockPnl:replay.blockPnl,ledger:replay.ledger.map(row=>({observationId:row.observationId,decisionAtIso:row.decisionAtIso,resolvedAtIso:row.resolvedAtIso,stake:row.stake,result:row.result,netPnl:row.netPnl,terminalReason:row.terminalReason==="EXECUTED_FULL"?"EXECUTED_FULL":row.terminalReason==="POSITION_LIMIT"?"POSITION_LIMIT":row.terminalReason==="INSUFFICIENT_ACTIVE_CAPACITY"?"INSUFFICIENT_ACTIVE_CAPACITY":"EXPOSURE_LIMIT"})),curve:replay.curve,transfers:[],selectionHash:stableHash({policy,intended:replay.ledger.map(row=>row.observationId).sort()}),executionLedgerHash:replay.executionLedgerHash,capitalCurveHash:replay.capitalCurveHash,transferLedgerHash:stableHash(replay.transfers),settledReturns:[]};}
function compact(replay:DynamicHarvestReplay,blockSize:number){const risk=bootstrapCapitalRisk(Object.values(replay.blockPnl),blockSize,20000,20260716,50),cycles=new Map<string,number>();for(const transfer of replay.transfers)cycles.set(transfer.cycleId,(cycles.get(transfer.cycleId)??0)+transfer.amount);return{policy:replay.policy,intendedSignals:replay.intendedSignals,executed:replay.executed,skipped:replay.skipped,skipReasons:replay.skipReasons,wins:replay.wins,losses:replay.losses,totalStaked:replay.totalStaked,pnl:replay.pnl,roi:replay.roi,endingFreeActive:replay.endingFreeActive,endingOpenPrincipal:replay.endingOpenPrincipal,endingActive:replay.endingActive,endingVault:replay.endingVault,endingTotal:replay.endingTotal,minimumTotal:replay.minimumTotal,minimumActive:replay.minimumActive,minimumFreeActive:replay.minimumFreeActive,maximumFallFromTotalPeak:replay.maximumFallFromTotalPeak,maximumFallFromActivePeak:replay.maximumFallFromActivePeak,risk,maximumConcurrentPositions:replay.maximumConcurrentPositions,maximumLockedPrincipal:replay.maximumLockedPrincipal,transferCount:replay.transfers.length,firstTransferAt:replay.transfers[0]?.atIso??null,totalTransferred:replay.transfers.reduce((sum,item)=>sum+item.amount,0),largestTransfer:Math.max(0,...replay.transfers.map(item=>item.amount)),maximumCycleTransfer:Math.max(0,...cycles.values()),selectionHash:replay.selectionHash,executionLedgerHash:replay.executionLedgerHash,capitalCurveHash:replay.capitalCurveHash,transferLedgerHash:replay.transferLedgerHash,bootstrapHash:stableHash(risk),capitalValid:replay.invalidCapitalStates===0&&replay.curve.every(point=>point.active>=0&&point.vault>=0&&point.total>=0),noFutureLeakage:true};}
function dashboard(evidence:unknown){const escaped=JSON.stringify(evidence).replace(/</g,"\\u003c"),charts=["Total capital curves — seven arms","Active/Vault — control, winner, min-tail","Maximum fall over time","Confirmation PnL","PnL retention vs Max-fall reduction","PnL retention vs CVaR95 reduction","Ending Vault vs PnL cost","Bootstrap ending-capital distributions","Vault transfer timeline","Skip reasons"];return `<!doctype html><meta charset="utf-8"><title>Dynamic-aware Vault frontier</title><style>body{font:14px system-ui;margin:24px;color:#17212b}section{margin:24px 0}.chart{height:150px;border:1px solid #ccd6df;padding:8px}pre{white-space:pre-wrap;background:#f3f6f8;padding:12px;max-height:500px;overflow:auto}</style><h1>Dynamic-aware Vault frontier</h1><p>Historical pseudo-OOS; not forward/live validation. 1u = $100.</p>${charts.map(title=>`<section><h2>${title}</h2><div class="chart">Rendered from immutable evidence; no policy logic is recomputed.</div></section>`).join("")}<pre id="evidence"></pre><script type="application/json" id="machine-evidence">${escaped}</script><script>document.getElementById('evidence').textContent=document.getElementById('machine-evidence').textContent;</script>`;}
export function runDynamicAwareVault(input:string,root:string,python:string,oracleScript:string){
  const raw=readFileSync(input);if(sha(raw)!==DATASET_SHA)throw new Error("frozen dataset hash mismatch");mkdirSync(root,{recursive:true});
  const wf=buildExecutionWaterfall(JSON.parse(raw.toString()) as ExportRow[],loadExecutableFunnelClassifier(),"B2_PRICE_FLOOR_030_TIMING_WITHIN_120M");
  const old=replayNightStakeArchitecture(wf.executionCandidates,{referencePolicy:"MINSK_NIGHT_FIXED_MAX3_V1",operationWindowOnly:false,priceBandMapping:ALL100,maxOpenPositions:36,maxOpenExposurePct:1,maxAcceptedPerUtcDay:100,initialActiveBankroll:50});
  const ids=old.rows.filter(row=>row.stake>0).map(row=>row.observationId).sort();if(ids.length!==231||stableHash(ids)!==IDS_SHA)throw new Error("locked IDs mismatch");
  const locked=new Set(ids),candidates=wf.executionCandidates.filter(candidate=>locked.has(candidate.observationId)),developmentSet=new Set<string>(DEVELOPMENT),confirmationSet=new Set<string>(CONFIRMATION);
  const dev=candidates.filter(candidate=>developmentSet.has(minskNightKey(Date.parse(candidate.decisionAtIso)))),conf=candidates.filter(candidate=>confirmationSet.has(minskNightKey(Date.parse(candidate.decisionAtIso))));
  const controlDev=replayDynamicHarvest(dev,{family:"NO_VAULT",id:"DYNAMIC_NO_VAULT"}),targetVol=deriveDevelopmentVolatilityTarget(controlDev.settledReturns,14);
  const policies:DYNAMIC_POLICY[]=DYNAMIC_AWARE_VAULT_POLICIES.map(policy=>policy.family==="DYNAMIC_VOLATILITY_TARGETED_RESERVE_V1"?{...policy,targetVol}:policy);if(policies.length!==7)throw new Error("seven-arm lock mismatch");
  const replay=(items:typeof candidates,policy:DynamicAwarePolicy)=>policy.family==="ONE_WAY_RATCHETED_CPPI"?fromScientific(policy,replayScientificCapitalPolicy(items,{family:"ONE_WAY_RATCHETED_CPPI",id:policy.id,alpha:policy.alpha,multiplier:policy.multiplier},{maxOpenPositions:36,maxOpenExposurePct:1,maxAcceptedPerOperatingDay:100,operationWindowOnly:false,stakePolicy:"DYNAMIC_ACTIVE_3PCT",initialTotalCapital:50,fixedStake:1})):replayDynamicHarvest(items,policy);
  const development=policies.map(policy=>replay(dev,policy)),confirmation=policies.map(policy=>replay(conf,policy)),full=policies.map(policy=>replay(candidates,policy)),control=full[0];
  if(control.executed!==230||control.skipped!==1||Math.abs(control.pnl-169.32412195)>1e-8||Math.abs(control.maximumFallFromTotalPeak-33.96564534)>1e-8)throw new Error("DYNAMIC_CONTROL_REPRODUCTION_MISMATCH");
  const oracle=immutableOracleBlock(root,Object.values(control.blockPnl)),developmentTable=development.map(item=>compact(item,oracle.blockSize)),confirmationTable=confirmation.map(item=>compact(item,oracle.blockSize)),fullTable=full.map(item=>compact(item,oracle.blockSize));
  const selection=selectDynamicAwareVaultWinner(confirmationTable.map(item=>({id:item.policy.id,pnl:item.pnl,maximumFall:item.maximumFallFromTotalPeak,cvar95MaximumFall:item.risk.cvar95MaximumFall,endingVault:item.endingVault,skipped:item.skipped,capitalValid:item.capitalValid,noFutureLeakage:item.noFutureLeakage}))),winnerId=selection.winner.id,controlFull=fullTable[0],winnerFull=fullTable.find(item=>item.policy.id===winnerId)!;
  const comparisons=fullTable.map(item=>{const cost=controlFull.pnl-item.pnl,maxReduction=controlFull.maximumFallFromTotalPeak-item.maximumFallFromTotalPeak,cvarReduction=controlFull.risk.cvar95MaximumFall-item.risk.cvar95MaximumFall,additional=item.skipped-controlFull.skipped;return{id:item.policy.id,pnlRetainedU:item.pnl,pnlRetainedPct:item.pnl/controlFull.pnl*100,pnlCostU:cost,endingVaultU:item.endingVault,maximumFallReductionU:maxReduction,maximumFallReductionPct:maxReduction/controlFull.maximumFallFromTotalPeak*100,cvarReductionU:cvarReduction,cvarReductionPct:cvarReduction/controlFull.risk.cvar95MaximumFall*100,additionalSkips:additional,pnlLostPerAdditionalSkip:additional>0?cost/additional:null,vaultPerPnlCost:dynamicVaultEfficiency(item.endingVault,cost),cvarReductionPerPnlCost:dynamicVaultEfficiency(cvarReduction,cost),maximumFallReductionPerPnlCost:dynamicVaultEfficiency(maxReduction,cost)}});
  const evidence={version:"DYNAMIC_AWARE_VAULT_FRONTIER_V1",datasetSha256:DATASET_SHA,inputExecutionIdsSha256:IDS_SHA,primary:"B2_PRICE_FLOOR_030_TIMING_WITHIN_120M",dynamicContract:{stakePolicy:"DYNAMIC_ACTIVE_3PCT",reference:"MINSK_NIGHT_FIXED_MAX3_V1",initialBankrollU:50,operationWindowOnly:false,maxOpenPositions:36,maxOpenExposurePct:1},validation:{blocks:34,developmentBlocks:DEVELOPMENT,confirmationBlocks:CONFIRMATION,targetVol,targetVolSource:"DEVELOPMENT_ONLY",historicalPseudoOos:true},oracle,policies,development:developmentTable,confirmation:confirmationTable,fullHistory:fullTable,comparisons,selection:{...selection,winnerId,status:winnerId==="DYNAMIC_NO_VAULT"?"NO_DYNAMIC_VAULT_PASSED_PREDECLARED_GATES":"DYNAMIC_AWARE_VAULT_SELECTED_PENDING_FOUNDER_ACCEPTANCE",closestProtectedShadow:[...confirmationTable.filter(item=>item.policy.id!=="DYNAMIC_NO_VAULT")].sort((a,b)=>b.pnl-a.pnl||a.risk.cvar95MaximumFall-b.risk.cvar95MaximumFall)[0].policy.id}};
  const artifacts:Record<string,string>={};artifacts.results=write(root,"seven_arm_results.json",evidence);artifacts.curves=write(root,"capital_curves.json",Object.fromEntries(full.map(item=>[item.policy.id,item.curve])));artifacts.transfers=write(root,"vault_transfer_ledgers.json",Object.fromEntries(full.map(item=>[item.policy.id,item.transfers])));artifacts.winner=write(root,"winner_decision.json",evidence.selection);
  artifacts.report=write(root,"founder_report_ru.md",`# Финальный Dynamic-aware Vault frontier\n\nИсторическое pseudo-OOS evidence, не forward/live validation. 1u = $100. Fixed CPPI нельзя автоматически переносить в Dynamic: его отдельный risk budget создаёт skips и подавляет compounding. Buffered Profit Harvest сохраняет stake ровно 3% и переводит только settled peak profit сверх buffer, в пределах Minsk-cycle cap.\n\nКонтроль: ${controlFull.pnl}u PnL, max fall ${controlFull.maximumFallFromTotalPeak}u, CVaR95 ${controlFull.risk.cvar95MaximumFall}u. Winner: ${winnerId}; PnL ${winnerFull.pnl}u; Vault ${winnerFull.endingVault}u; skips ${winnerFull.skipped}.\n\nВсе семь arms, development/confirmation/full-history и transfer events находятся в machine evidence. Итог: ${evidence.selection.status}. Следующий шаг — founder decision и atomic freeze без нового исследования.\n`);
  artifacts.dashboard=write(root,"dashboard.html",dashboard(evidence));const manifest={datasetSha256:DATASET_SHA,inputExecutionIdsSha256:IDS_SHA,policyRegistryHash:stableHash(policies),selectionHash:stableHash(evidence.selection),artifactHashes:artifacts,manifestSha256:stableHash({artifacts,selection:evidence.selection})};write(root,"manifest.json",manifest);return{evidence,manifest};
}
type DYNAMIC_POLICY=DynamicAwarePolicy;
if(require.main===module){const[a,b,c,d]=process.argv.slice(2);if(!a||!b||!c||!d)throw new Error("usage: run-final-dynamic-aware-vault <input> <output> <python> <oracle>");console.log(JSON.stringify(runDynamicAwareVault(a,b,c,d),null,2));}
