import type { TestimonialCard } from './types';

export const TESTIMONIAL_CARDS: TestimonialCard[] = [
  {
    id: 'card-7-draftkings-knicks',
    avatarUrl: 'https://i.pravatar.cc/150?img=25',
    username: '@Breeze7054',
    platform: 'instagram',
    quote: 'Signal quality is ELITE. Knicks Game 1 vs Cavs — PolyProPicks showed 78 confidence two hours before tip. Hart dropped 26, won in OT. Entered at +145 on DraftKings. $340 total payout on $140 in.',
    verifiedEvent: 'Knicks win ECF Game 1 (OT) · May 19',
    verifiedPnl: '+$340',
    screenshot: {
      type: 'draftkings',
      league: 'NBA · Eastern Conference Finals',
      event: 'New York Knicks @ Cleveland Cavaliers · Game 1',
      selection: 'Knicks Moneyline',
      result: 'Knicks 114, Cavaliers 109 (OT) ✓',
      odds: '+145',
      totalPayout: '$340.00',
      wager: '$140.00',
      profit: '+$200.00',
      betId: 'Bet #DK-9831722-AA',
    },
  },
  {
    id: 'card-1-arsenal-ucl',
    avatarUrl: 'https://i.pravatar.cc/150?img=11',
    username: '@propsadoodledoo',
    platform: 'tiktok',
    quote: "Best signal feed I've found. Caught Arsenal advancing past Atlético before the line moved. Signal confidence hit 81 — I entered Yes at 55¢ and watched it close at a dollar.",
    verifiedEvent: 'Arsenal advance · UCL Semifinal · May 5',
    verifiedPnl: '+$205',
    screenshot: {
      type: 'polymarket',
      portfolio: '$412.50', cash: '$64.20', flag: '🇺🇸',
      rows: [
        { activity: 'Sell', emoji: '🏟️', eventName: 'Arsenal to advance past Atlético Madrid — UCL Semifinals?', pill: 'yes', pillPrice: '100¢', shares: '41 shares', value: '+$205.00', valueType: 'pos', timeAgo: '18d ago', highlight: true },
        { activity: 'Buy',  emoji: '🏟️', eventName: 'Arsenal to advance past Atlético Madrid — UCL Semifinals?', pill: 'yes', pillPrice: '55¢',  shares: '41 shares', value: '-$22.55', valueType: 'neg', timeAgo: '22d ago' },
        { activity: 'Buy',  emoji: '⚽',  eventName: 'Exact Score: Atlético de Madrid 1-1 Arsenal FC?',           pill: 'yes', pillPrice: '15¢',  shares: '66.7 shares', value: '-$10.25', valueType: 'neg', timeAgo: '23d ago' },
      ],
    },
  },
  {
    id: 'card-6-fanduel-arsenal',
    avatarUrl: 'https://i.pravatar.cc/150?img=33',
    username: 'David Smith',
    platform: 'x',
    quote: 'PolyProPicks gut-checks me before every entry. Arsenal advancing past Atlético — signal confidence hit 81. Entered on FanDuel at +200. They won 1-0 in the second leg and I hit a $205 payout on a $100 wager.',
    verifiedEvent: 'Arsenal advance · UCL Semifinal · May 5',
    verifiedPnl: '+$205',
    screenshot: {
      type: 'fanduel',
      league: 'UEFA Champions League — Semifinal',
      event: 'Arsenal vs Atlético Madrid',
      selection: 'Arsenal to Advance (Moneyline)',
      result: 'Arsenal 1-0 Atlético · 2-1 on Agg. ✓ Final',
      date: 'UEFA UCL · May 5',
      wager: '$100.00',
      payout: '$205.00',
      netProfit: '+$105.00',
      betId: 'Bet #FD-2847291-K',
    },
  },
  {
    id: 'card-2-knicks-ecf',
    avatarUrl: 'https://i.pravatar.cc/150?img=32',
    username: '@Breeze7054',
    platform: 'instagram',
    quote: 'After a week of testing I can say the signal quality is ELITE. Knicks Game 1 vs Cavs — signal came in at 44¢ two hours before tip. Hart dropped 26, won in OT. Closed at a dollar.',
    verifiedEvent: 'Knicks win ECF Game 1 (OT) · May 19',
    verifiedPnl: '+$340',
    screenshot: {
      type: 'polymarket',
      portfolio: '$573.20', cash: '$91.40', flag: '🇺🇸',
      rows: [
        { activity: 'Sell', emoji: '🏀', eventName: 'Knicks to win ECF Game 1 vs Cavaliers?',     pill: 'yes', pillPrice: '100¢', shares: '60 shares', value: '+$340.00', valueType: 'pos', timeAgo: '4d ago',  highlight: true },
        { activity: 'Buy',  emoji: '🏀', eventName: 'Knicks to win ECF Game 1 vs Cavaliers?',     pill: 'yes', pillPrice: '44¢',  shares: '60 shares', value: '-$26.40', valueType: 'neg', timeAgo: '4d ago' },
        { activity: 'Buy',  emoji: '🏀', eventName: 'Pistons to win NBA R1 Game 1 vs Cavaliers?', pill: 'no',  pillPrice: '38¢',  shares: '40 shares', value: '-$15.20', valueType: 'neg', timeAgo: '18d ago' },
      ],
    },
  },
  {
    id: 'card-3-thunder-wcf',
    avatarUrl: 'https://i.pravatar.cc/150?img=52',
    username: 'David Smith',
    platform: 'x',
    quote: "PolyProPicks gut-checks me when I'm about to make a lazy entry. OKC bouncing back in Game 2 after Wembanyama's overtime — signal confidence 76, I trusted it. Thunder won 122-113.",
    verifiedEvent: 'Thunder win WCF Game 2 · 122-113 · May 21',
    verifiedPnl: '+$186',
    screenshot: {
      type: 'polymarket',
      portfolio: '$153.44', cash: '$92.76', flag: '🇺🇸',
      rows: [
        { activity: 'Sell', emoji: '🏀', eventName: 'OKC Thunder to win WCF Game 2 vs San Antonio Spurs?', pill: 'yes', pillPrice: '100¢', shares: '31.7 shares', value: '+$186.00', valueType: 'pos', timeAgo: '2d ago', highlight: true },
        { activity: 'Buy',  emoji: '🏀', eventName: 'OKC Thunder to win WCF Game 2 vs San Antonio Spurs?', pill: 'yes', pillPrice: '41¢',  shares: '31.7 shares', value: '-$13.00',  valueType: 'neg', timeAgo: '2d ago' },
        { activity: 'Buy',  emoji: '🏀', eventName: 'Spurs to win WCF Game 1 vs Thunder (2OT)?',           pill: 'no',  pillPrice: '12¢',  shares: '80.5 shares', value: '-',        valueType: 'neu', timeAgo: '4d ago' },
      ],
    },
  },
  {
    id: 'card-4-psg-ucl',
    avatarUrl: 'https://i.pravatar.cc/150?img=47',
    username: '@sharpflow_k',
    platform: 'telegram',
    quote: 'PSG vs Bayern — signal showed sharp money data at 73 confidence. Entered at 62¢ after the 5-4 first leg. They drew 1-1 in Munich and advanced 6-5. Closed at a dollar.',
    verifiedEvent: 'PSG advance · UCL Semifinal · May 6',
    verifiedPnl: '+$247',
    screenshot: {
      type: 'polymarket',
      portfolio: '$312.88', cash: '$44.10', flag: '🇺🇸',
      rows: [
        { activity: 'Sell', emoji: '🏆', eventName: 'PSG to advance past Bayern Munich — UCL Semifinals?', pill: 'yes', pillPrice: '100¢', shares: '40 shares', value: '+$247.00', valueType: 'pos', timeAgo: '17d ago', highlight: true },
        { activity: 'Buy',  emoji: '🏆', eventName: 'PSG to advance past Bayern Munich — UCL Semifinals?', pill: 'yes', pillPrice: '62¢',  shares: '40 shares', value: '-$24.80',  valueType: 'neg', timeAgo: '22d ago' },
        { activity: 'Buy',  emoji: '⚽',  eventName: 'Exact Score: Atlético de Madrid 1-1 Arsenal FC?',    pill: 'yes', pillPrice: '15¢',  shares: '66.7 shares', value: '-$10.25', valueType: 'neg', timeAgo: '23d ago' },
      ],
    },
  },
  {
    id: 'card-5-canadiens-ecf',
    avatarUrl: 'https://i.pravatar.cc/150?img=68',
    username: '@polyedge_m',
    platform: 'tiktok',
    quote: "Not only does PolyProPicks gut-check me before entries — Canadiens Game 1 vs Carolina signal hit 78 confidence. MTL was the underdog. They won 6-2 and ended Carolina's perfect run. +$318.",
    verifiedEvent: 'Canadiens win ECF G1 · 6-2 · May 21',
    verifiedPnl: '+$318',
    screenshot: {
      type: 'polymarket',
      portfolio: '$488.30', cash: '$77.50', flag: '🇺🇸',
      rows: [
        { activity: 'Sell', emoji: '🏒', eventName: 'Canadiens to win ECF Game 1 vs Hurricanes?',     pill: 'yes', pillPrice: '100¢', shares: '53 shares', value: '+$318.00', valueType: 'pos', timeAgo: '2d ago',  highlight: true },
        { activity: 'Buy',  emoji: '🏒', eventName: 'Canadiens to win ECF Game 1 vs Hurricanes?',     pill: 'yes', pillPrice: '38¢',  shares: '53 shares', value: '-$20.14',  valueType: 'neg', timeAgo: '2d ago' },
        { activity: 'Buy',  emoji: '🏒', eventName: 'Golden Knights to win WCF Game 1 vs Avalanche?', pill: 'yes', pillPrice: '51¢',  shares: '30 shares', value: '+$147.00', valueType: 'pos', timeAgo: '3d ago' },
      ],
    },
  },
];
