/**
 * LIVE_RUNTIME_DATA_V1 -- production runtime aggregate for MODELING_DASHBOARD.html's
 * LIVE panel. Generated by scripts/modeling/refresh-live-modeling-dashboard.ts
 * (READ-ONLY: night_event_reservations scoped by plan_date_minsk; event_execution_queue
 * traced by reservation_id; executor_order_events read for exact clob_order_id /
 * raw_event_json->>'state' / stake_usd fields; bet_execution_ledger read only for
 * settled_at IS NOT NULL rows). Production writes = 0. Previously captured aggregate
 * days -- including any Architect-verified seeded snapshot -- are preserved verbatim;
 * a failed refresh NEVER deletes them, and a successful refresh only replaces the
 * CURRENT Minsk plan date's own snapshot.
 */
window.POLYPROPICKS_LIVE_RUNTIME_DATA = {
  "ARTIFACT": "LIVE_RUNTIME_DATA_V1",
  "GENERATED_AT": "2026-09-21T20:00:00.000Z",
  "status": "OK",
  "productionProjectRef": "nbnldzfsxffztsfrrxqy",
  "latestMinskDate": "2026-09-21",
  "lastRefreshAttempt": {
    "at": "2026-09-21T20:02:07.245Z",
    "stopReason": "STOPPED_PRODUCTION_ENV_MISSING: SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY absent in this execution context."
  },
  "days": [
    {
      "minskDate": "2026-09-21",
      "provenance": {
        "source": "ARCHITECT_VERIFIED_PRODUCTION_AGGREGATE",
        "planDate": "2026-09-21",
        "productionProjectRef": "nbnldzfsxffztsfrrxqy",
        "productionWrites": 0,
        "realizedPnlStatus": "PENDING_NOT_SETTLED"
      },
      "reservations": {
        "total": 25,
        "reserved": 15,
        "queued": 10,
        "status": "OK"
      },
      "queue": {
        "total": 10,
        "ready": 0,
        "executed": 9,
        "expired": 1,
        "other": 0,
        "status": "OK"
      },
      "orders": {
        "total": 10,
        "clobOrderN": 10,
        "acceptedOpenN": 10,
        "submittedStakeUsd": 31,
        "status": "OK"
      },
      "settled": {
        "status": "PENDING_NOT_SETTLED",
        "count": 0,
        "realized_pnl_usd": null,
        "source": null,
        "note": "0 authoritative settled_at IS NOT NULL rows observed -- never inferring realized P&L from potential payout, accepted_open, or gross_profit_if_win."
      },
      "generatedAt": "2026-09-21T20:00:00.000Z"
    }
  ]
};
