/**
 * LIVE_RUNTIME_DATA_V1 -- production runtime aggregate for MODELING_DASHBOARD.html's
 * LIVE panel. Generated by scripts/modeling/refresh-live-modeling-dashboard.ts
 * (READ-ONLY: SELECT/count-only reads against night_event_reservations /
 * event_execution_queue / executor_order_events / bet_execution_ledger).
 * Production writes = 0. This run could not reach production (see stopReason
 * below) -- previously captured aggregate days are preserved verbatim; no
 * historical day is silently rewritten.
 */
window.POLYPROPICKS_LIVE_RUNTIME_DATA = {
  "ARTIFACT": "LIVE_RUNTIME_DATA_V1",
  "GENERATED_AT": "2026-09-21T19:46:34.356Z",
  "status": "STOPPED",
  "stopReason": "STOPPED_PRODUCTION_ENV_MISSING: SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY absent in this execution context.",
  "days": []
};
